import type { OutlookMessage, EmailFolder } from "./microsoft-graph"

export const MOCK_FOLDERS: EmailFolder[] = [
  { id: "inbox", displayName: "Caixa de Entrada", unreadCount: 7, totalCount: 156 },
  { id: "sentitems", displayName: "Enviados", unreadCount: 0, totalCount: 89 },
  { id: "drafts", displayName: "Rascunhos", unreadCount: 0, totalCount: 3 },
  { id: "deleteditems", displayName: "Lixeira", unreadCount: 0, totalCount: 12 },
  { id: "archive", displayName: "Arquivo", unreadCount: 0, totalCount: 234 },
  { id: "junkemail", displayName: "Spam", unreadCount: 0, totalCount: 8 },
]

const now = new Date()
function daysAgo(d: number): string {
  const date = new Date(now.getTime() - d * 86400000)
  return date.toISOString()
}
function hoursAgo(h: number): string {
  const date = new Date(now.getTime() - h * 3600000)
  return date.toISOString()
}

export const MOCK_MESSAGES: OutlookMessage[] = [
  // 3 intimações
  {
    id: "mock-1",
    subject: "INTIMAÇÃO ELETRÔNICA - Proc. 0028131-45.2025.8.16.0001 - Prazo 15 dias",
    bodyPreview: "Fica Vossa Senhoria intimado(a) para, no prazo de 15 (quinze) dias úteis, apresentar contestação nos autos...",
    body: { contentType: "HTML", content: "<p>Poder Judiciário do Estado do Paraná<br/>1ª Vara Cível da Comarca de Maringá</p><p>Processo nº 0028131-45.2025.8.16.0001<br/>Classe: Recuperação Judicial<br/>Requerente: Agroindustrial São Paulo Ltda</p><p>Fica Vossa Senhoria intimado(a) para, no prazo de 15 (quinze) dias úteis, apresentar <strong>contestação</strong> nos autos do processo em referência, sob pena de revelia.</p><p>Maringá/PR, 17 de fevereiro de 2026.</p><p><em>Intimação gerada automaticamente pelo sistema PJe</em></p>" },
    from: { name: "PJe - TJPR", email: "intimacao@tjpr.jus.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: hoursAgo(2),
    isRead: false,
    hasAttachments: true,
    importance: "high",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-1",
  },
  {
    id: "mock-2",
    subject: "INTIMAÇÃO - Proc. 5001234-89.2025.4.04.7001 - Decisão interlocutória",
    bodyPreview: "Intimação para ciência da decisão que deferiu a tutela de urgência requerida nos autos...",
    body: { contentType: "HTML", content: "<p>Tribunal Regional Federal da 4ª Região<br/>2ª Vara Federal de Maringá/PR</p><p>Processo nº 5001234-89.2025.4.04.7001</p><p>Intimo as partes para ciência da <strong>decisão interlocutória</strong> proferida nos autos, que deferiu a tutela de urgência para suspensão da exigibilidade do crédito tributário.</p><p>Prazo para recurso: 15 dias úteis.</p>" },
    from: { name: "PJe - TRF4", email: "intimacao@trf4.jus.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: hoursAgo(5),
    isRead: false,
    hasAttachments: false,
    importance: "high",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-2",
  },
  {
    id: "mock-3",
    subject: "DJe - Publicação em nome de OAB/PR 12345 - 18/02/2026",
    bodyPreview: "Processo 0045678-12.2024.8.16.0001. Despacho: Defiro o pedido de habilitação retardatária de crédito...",
    body: { contentType: "HTML", content: "<p><strong>DIÁRIO DA JUSTIÇA ELETRÔNICO</strong><br/>Tribunal de Justiça do Paraná</p><p>Publicação em nome de: OAB/PR 12345 - Dr. Jean Ricardo</p><hr/><p><strong>Processo:</strong> 0045678-12.2024.8.16.0001<br/><strong>Despacho:</strong> Defiro o pedido de habilitação retardatária de crédito formulado por Banco Itaú S.A., no valor de R$ 1.234.567,89. Intime-se o Administrador Judicial para atualização do QGC.</p>" },
    from: { name: "DJe - TJPR", email: "dje@tjpr.jus.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: hoursAgo(8),
    isRead: false,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-3",
  },
  // 3 comunicações de credores
  {
    id: "mock-4",
    subject: "RE: Proposta de acordo - Agroindustrial São Paulo - Classe III Quirografário",
    bodyPreview: "Prezado Dr. Jean, em atenção à proposta apresentada, o Banco do Brasil S.A. contrapropõe o pagamento...",
    body: { contentType: "HTML", content: "<p>Prezado Dr. Jean,</p><p>Em atenção à proposta apresentada em nome da recuperanda Agroindustrial São Paulo Ltda., o <strong>Banco do Brasil S.A.</strong> contrapropõe o pagamento do crédito quirografário no valor atualizado de R$ 2.456.789,00 nas seguintes condições:</p><ul><li>Deságio de 45% sobre o valor atualizado</li><li>Pagamento em 36 parcelas mensais</li><li>Carência de 12 meses</li><li>Correção pelo IPCA + 3% a.a.</li></ul><p>Aguardamos manifestação.</p><p>Atenciosamente,<br/>Maria Fernanda Costa<br/>Gerente Jurídico - Banco do Brasil S.A.</p>" },
    from: { name: "Maria Fernanda Costa", email: "maria.costa@bb.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [{ name: "Jurídico BB", email: "juridico.rj@bb.com.br" }],
    receivedAt: hoursAgo(3),
    isRead: false,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "flagged" },
    conversationId: "conv-4",
  },
  {
    id: "mock-5",
    subject: "Habilitação de Crédito - FIDC Amazônia - Proc. 0028131",
    bodyPreview: "Prezado Administrador Judicial, encaminhamos em anexo petição de habilitação de crédito...",
    body: { contentType: "HTML", content: "<p>Prezados,</p><p>Encaminhamos em anexo a petição de <strong>habilitação de crédito</strong> do FIDC Amazônia Multissetorial, cessionário do crédito originalmente detido por Fornecedora ABC Ltda.</p><p>Valor do crédito: R$ 890.345,67<br/>Classe: III - Quirografário<br/>Natureza: Comercial (duplicatas mercantis)</p><p>Documentação comprobatória em anexo.</p><p>Dr. Roberto Almeida<br/>OAB/SP 234567</p>" },
    from: { name: "Roberto Almeida", email: "roberto@almeida.adv.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(1),
    isRead: true,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-5",
  },
  {
    id: "mock-6",
    subject: "Itaú BBA - Renegociação CCB nº 456789 - URGENTE",
    bodyPreview: "Informamos que o prazo para adesão ao programa de renegociação de créditos se encerra em 28/02/2026...",
    body: { contentType: "HTML", content: "<p>Prezado Dr. Jean Ricardo,</p><p>Informamos que o prazo para adesão ao programa de renegociação de créditos garantidos se encerra em <strong>28/02/2026</strong>.</p><p>Para a CCB nº 456789, garantida por alienação fiduciária de imóvel (matrícula 12345 CRI Maringá), as condições oferecidas são:</p><ul><li>Manutenção do valor integral do crédito</li><li>Prazo de 48 meses com 6 meses de carência</li><li>Taxa: CDI + 2,5% a.a.</li></ul><p>Solicitamos urgência na resposta.</p><p>Atenciosamente,<br/>Departamento de Reestruturação de Créditos<br/>Itaú BBA</p>" },
    from: { name: "Itaú BBA Reestruturação", email: "reestruturacao@itaubba.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(1),
    isRead: false,
    hasAttachments: true,
    importance: "high",
    flag: { flagStatus: "flagged" },
    conversationId: "conv-6",
  },
  // 2 clientes
  {
    id: "mock-7",
    subject: "Dúvida sobre andamento da recuperação judicial",
    bodyPreview: "Bom dia Dr. Jean, gostaria de saber como está o andamento do processo de recuperação judicial...",
    body: { contentType: "HTML", content: "<p>Bom dia Dr. Jean,</p><p>Gostaria de saber como está o andamento do processo de recuperação judicial. A assembleia geral de credores já tem data marcada?</p><p>Também preciso de uma atualização sobre as negociações com o Banco do Brasil e o Itaú. O fluxo de caixa da empresa está apertado e precisamos definir as condições de pagamento o quanto antes.</p><p>Podemos agendar uma reunião para esta semana?</p><p>Atenciosamente,<br/>Carlos Eduardo Silva<br/>Diretor - Agroindustrial São Paulo Ltda.</p>" },
    from: { name: "Carlos Eduardo Silva", email: "carlos@agroindustrial-sp.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: hoursAgo(6),
    isRead: false,
    hasAttachments: false,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-7",
  },
  {
    id: "mock-8",
    subject: "RE: Documentação para operação de crédito rural - Fazenda Bom Retiro",
    bodyPreview: "Dr. Jean, segue em anexo toda a documentação solicitada para a operação de crédito rural...",
    body: { contentType: "HTML", content: "<p>Dr. Jean,</p><p>Segue em anexo toda a documentação solicitada para a operação de crédito rural junto ao BNDES:</p><ul><li>Matrícula atualizada do imóvel rural</li><li>CCIR e ITR dos últimos 5 anos</li><li>Laudo de avaliação do imóvel</li><li>Balanço patrimonial 2025</li><li>Declaração de produção</li></ul><p>A safra está prevista para março e precisamos da liberação até lá.</p><p>Abs,<br/>João Pedro Martins<br/>Fazenda Bom Retiro</p>" },
    from: { name: "João Pedro Martins", email: "joaopedro@fazendabomretiro.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(2),
    isRead: true,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-8",
  },
  // 2 propostas de acordo
  {
    id: "mock-9",
    subject: "Proposta de Acordo - Credor: Transportadora Rodobrás Ltda.",
    bodyPreview: "Ilustre Colega, nosso cliente Transportadora Rodobrás Ltda. está disposto a aceitar...",
    body: { contentType: "HTML", content: "<p>Ilustre Colega Dr. Jean Ricardo,</p><p>Nosso cliente, <strong>Transportadora Rodobrás Ltda.</strong>, credor quirografário da recuperanda Agroindustrial São Paulo Ltda., está disposto a aceitar acordo nos seguintes termos:</p><ul><li>Valor do crédito: R$ 345.678,90</li><li>Deságio proposto: 50%</li><li>Valor a receber: R$ 172.839,45</li><li>Pagamento à vista, em até 30 dias após homologação</li></ul><p>Aguardamos contraproposta ou aceitação.</p><p>Dr. Ana Paula Rodrigues<br/>OAB/PR 67890</p>" },
    from: { name: "Ana Paula Rodrigues", email: "ana.paula@rodriguesadv.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(1),
    isRead: true,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "flagged" },
    conversationId: "conv-9",
  },
  {
    id: "mock-10",
    subject: "Acordo extrajudicial - Fornecedora Industrial MG",
    bodyPreview: "Prezado, a Fornecedora Industrial MG aceita os termos propostos para pagamento do débito...",
    body: { contentType: "HTML", content: "<p>Prezado Dr. Jean,</p><p>A Fornecedora Industrial MG Ltda. <strong>aceita os termos propostos</strong> para pagamento do débito de R$ 567.890,12:</p><ul><li>Deságio de 35%</li><li>24 parcelas mensais</li><li>Carência de 6 meses</li><li>Correção IPCA</li></ul><p>Favor encaminhar o termo de acordo para assinatura.</p><p>Dr. Marcos Vinícius<br/>OAB/MG 11223</p>" },
    from: { name: "Marcos Vinícius", email: "marcos@vinicius.adv.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(3),
    isRead: true,
    hasAttachments: false,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-10",
  },
  // 2 internos
  {
    id: "mock-11",
    subject: "Reunião de equipe - Estratégia AGC Agroindustrial São Paulo",
    bodyPreview: "Pessoal, precisamos alinhar a estratégia para a Assembleia Geral de Credores...",
    body: { contentType: "HTML", content: "<p>Pessoal,</p><p>Precisamos alinhar a estratégia para a <strong>Assembleia Geral de Credores</strong> da Agroindustrial São Paulo, marcada para 15/03/2026.</p><p>Pauta da reunião:<br/>1. Status das negociações por classe<br/>2. Projeções de votação (quórum)<br/>3. Estratégia cram down (cenário pessimista)<br/>4. Documentação pendente Art. 53</p><p>Reunião: amanhã (19/02) às 14h na sala de reuniões.</p><p>Jean Ricardo</p>" },
    from: { name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" },
    toRecipients: [{ name: "Equipe JRCLaw", email: "equipe@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: hoursAgo(1),
    isRead: true,
    hasAttachments: false,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-11",
  },
  {
    id: "mock-12",
    subject: "Análise financeira - Plano RJ atualizado",
    bodyPreview: "Jean, finalizei a análise financeira do plano de recuperação atualizado. Os números...",
    body: { contentType: "HTML", content: "<p>Jean,</p><p>Finalizei a análise financeira do plano de recuperação atualizado. Os números mostram que:</p><ul><li>Classe I (Trabalhista): pagamento integral é viável em 12 meses</li><li>Classe II (Garantia Real): deságio máximo de 20% para manter adesão</li><li>Classe III (Quirografário): deságio de 40-50% em 48 parcelas é o cenário mais realista</li><li>Classe IV (ME/EPP): pagamento em 36 meses sem deságio</li></ul><p>Planilha detalhada em anexo.</p><p>Abs,<br/>Fernanda - Equipe JRCLaw</p>" },
    from: { name: "Fernanda Oliveira", email: "fernanda@jrclaw.com.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(2),
    isRead: true,
    hasAttachments: true,
    importance: "normal",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-12",
  },
  // 3 marketing/newsletter
  {
    id: "mock-13",
    subject: "Newsletter Jurídica - Alterações na Lei 11.101/2005",
    bodyPreview: "As recentes alterações promovidas pela Lei 14.112/2020 na Lei de Recuperação Judicial...",
    body: { contentType: "HTML", content: "<p><strong>Newsletter Jurídica Semanal</strong></p><p>As recentes alterações promovidas pela Lei 14.112/2020 continuam gerando impactos significativos nos processos de recuperação judicial em curso. Destacamos os principais pontos de atenção para 2026.</p>" },
    from: { name: "IBAJUD", email: "newsletter@ibajud.org.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(3),
    isRead: true,
    hasAttachments: false,
    importance: "low",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-13",
  },
  {
    id: "mock-14",
    subject: "Convite: Congresso Nacional de Direito Empresarial 2026",
    bodyPreview: "Prezado(a) advogado(a), é com satisfação que convidamos para o XII Congresso Nacional...",
    body: { contentType: "HTML", content: "<p>Prezado(a) Dr(a),</p><p>É com satisfação que convidamos para o <strong>XII Congresso Nacional de Direito Empresarial 2026</strong>.</p><p>Data: 20 a 22 de maio de 2026<br/>Local: Centro de Convenções de São Paulo</p>" },
    from: { name: "OAB Nacional", email: "eventos@oab.org.br" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(5),
    isRead: true,
    hasAttachments: false,
    importance: "low",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-14",
  },
  {
    id: "mock-15",
    subject: "Thomson Reuters - Atualização Jurisprudencial Semanal",
    bodyPreview: "Confira as principais decisões da semana em Recuperação Judicial e Falência...",
    body: { contentType: "HTML", content: "<p><strong>Atualização Jurisprudencial</strong></p><p>Confira as principais decisões da semana em Recuperação Judicial e Falência nos Tribunais Superiores.</p><p>1. STJ - REsp 2.345.678: Extensão do stay period em caso de pandemia<br/>2. TJSP - AI 2.123.456: Cram down e quórum alternativo<br/>3. TJPR - AI 0.987.654: Crédito extraconcursal de fornecedor essencial</p>" },
    from: { name: "Thomson Reuters", email: "alertas@thomsonreuters.com" },
    toRecipients: [{ name: "Dr. Jean Ricardo", email: "jean@jrclaw.com.br" }],
    ccRecipients: [],
    receivedAt: daysAgo(4),
    isRead: true,
    hasAttachments: false,
    importance: "low",
    flag: { flagStatus: "notFlagged" },
    conversationId: "conv-15",
  },
]

export function getMockMessages(folderId: string): OutlookMessage[] {
  if (folderId === "inbox") return MOCK_MESSAGES
  if (folderId === "sentitems") return MOCK_MESSAGES.filter(m => m.from.email === "jean@jrclaw.com.br")
  if (folderId === "drafts") return []
  return []
}

export function getMockMessage(id: string): OutlookMessage | undefined {
  return MOCK_MESSAGES.find(m => m.id === id)
}
