import { PrismaClient, DeadlineType, DeadlineCategory, CountingType, PieceType, PartyRole } from "@prisma/client";

const prisma = new PrismaClient();

interface CatalogEntry {
  type: DeadlineType;
  displayName: string;
  shortName: string;
  category: DeadlineCategory;
  legalBasis: string | null;
  defaultDays: number;
  countingType: CountingType;
  isExtendable: boolean;
  isFatal: boolean;
  defaultPriority: string;
  color: string;
  icon: string | null;
  doubleForPublicEntity: boolean;
  doubleForDefensoria: boolean;
  specialRules: Record<string, unknown> | null;
  sortOrder: number;
}

interface TriggerEntry {
  deadlineType: DeadlineType;
  triggerPieceType: PieceType;
  triggerDescription: string;
  targetRole: PartyRole;
  isSuggestion: boolean;
  isDefault: boolean;
  notes: string | null;
}

// ============================================================
// CATÁLOGO COMPLETO DE TIPOS DE PRAZO (80+ entries)
// ============================================================
const catalogEntries: CatalogEntry[] = [
  // ── DEFESA E RESPOSTA ──────────────────────────────────
  {
    type: "CONTESTACAO",
    displayName: "Contestação",
    shortName: "Contest.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 335, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "shield",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { prorrogacaoConvencao: true, litisconsorcioAdd: 15 },
    sortOrder: 10,
  },
  {
    type: "RECONVENCAO",
    displayName: "Reconvenção",
    shortName: "Reconv.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 343, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "sword",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { mesmoTopoContestacao: true },
    sortOrder: 11,
  },
  {
    type: "REPLICA",
    displayName: "Réplica",
    shortName: "Réplica",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 351, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#EA580C",
    icon: "message-square-reply",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 12,
  },
  {
    type: "IMPUGNACAO_VALOR_CAUSA",
    displayName: "Impugnação ao Valor da Causa",
    shortName: "Imp.Val.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 293, §1º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#EA580C",
    icon: "calculator",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { preliminarContestacao: true },
    sortOrder: 13,
  },
  {
    type: "IMPUGNACAO_JUSTICA_GRATUITA",
    displayName: "Impugnação à Justiça Gratuita",
    shortName: "Imp.JG",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 100, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "MEDIA",
    color: "#F59E0B",
    icon: "badge-dollar-sign",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 14,
  },
  {
    type: "IMPUGNACAO_CUMPRIMENTO",
    displayName: "Impugnação ao Cumprimento de Sentença",
    shortName: "Imp.Cumpr.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 525, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "gavel",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { aposIntimacaoPagamento: true },
    sortOrder: 15,
  },
  {
    type: "EXCECAO_PRE_EXECUTIVIDADE",
    displayName: "Exceção de Pré-Executividade",
    shortName: "Exc.Pré-Ex.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Súmula 393, STJ",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#EA580C",
    icon: "shield-alert",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { semPrazoLegal: true, prazoConvencional: true },
    sortOrder: 16,
  },
  {
    type: "EMBARGOS_EXECUCAO",
    displayName: "Embargos à Execução",
    shortName: "Emb.Exec.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 915, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "shield-check",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { aPartirDaJuntadaMandado: true },
    sortOrder: 17,
  },
  {
    type: "EMBARGOS_TERCEIRO",
    displayName: "Embargos de Terceiro",
    shortName: "Emb.3º",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 675, CPC",
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "user-shield",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { atéAdjudicacao: true },
    sortOrder: 18,
  },
  {
    type: "EMBARGOS_DECLARACAO",
    displayName: "Embargos de Declaração",
    shortName: "Emb.Decl.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 1.023, CPC",
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "file-question",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { interruptivoPrazoRecursal: true },
    sortOrder: 19,
  },
  {
    type: "MANIFESTACAO",
    displayName: "Manifestação",
    shortName: "Manif.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 218, §3º, CPC",
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#F59E0B",
    icon: "message-circle",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { prazoJudicial: true },
    sortOrder: 20,
  },
  {
    type: "ESPECIFICACAO_PROVAS",
    displayName: "Especificação de Provas",
    shortName: "Espec.Prov.",
    category: "DEFESA_RESPOSTA",
    legalBasis: "Art. 357, §4º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#EA580C",
    icon: "list-checks",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 21,
  },

  // ── RECURSAIS ──────────────────────────────────────────
  {
    type: "APELACAO",
    displayName: "Apelação",
    shortName: "Apel.",
    category: "RECURSAL",
    legalBasis: "Art. 1.003, §5º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-up-circle",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 100,
  },
  {
    type: "CONTRARRAZOES_APELACAO",
    displayName: "Contrarrazões de Apelação",
    shortName: "C/R Apel.",
    category: "RECURSAL",
    legalBasis: "Art. 1.010, §1º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-down-circle",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 101,
  },
  {
    type: "AGRAVO_INSTRUMENTO",
    displayName: "Agravo de Instrumento",
    shortName: "AI",
    category: "RECURSAL",
    legalBasis: "Art. 1.003, §5º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-up-right",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 102,
  },
  {
    type: "CONTRARRAZOES_AGRAVO",
    displayName: "Contrarrazões de Agravo",
    shortName: "C/R Agravo",
    category: "RECURSAL",
    legalBasis: "Art. 1.019, II, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-down-right",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 103,
  },
  {
    type: "AGRAVO_INTERNO",
    displayName: "Agravo Interno",
    shortName: "Ag.Int.",
    category: "RECURSAL",
    legalBasis: "Art. 1.021, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-up",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 104,
  },
  {
    type: "RECURSO_ORDINARIO",
    displayName: "Recurso Ordinário",
    shortName: "RO",
    category: "RECURSAL",
    legalBasis: "Art. 1.003, §5º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#DC2626",
    icon: "arrow-big-up",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 105,
  },
  {
    type: "RECURSO_ESPECIAL",
    displayName: "Recurso Especial",
    shortName: "REsp",
    category: "RECURSAL",
    legalBasis: "Art. 1.003, §5º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "scale",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { prequestionamento: true },
    sortOrder: 106,
  },
  {
    type: "CONTRARRAZOES_RESP",
    displayName: "Contrarrazões de REsp",
    shortName: "C/R REsp",
    category: "RECURSAL",
    legalBasis: "Art. 1.030, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "scale",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 107,
  },
  {
    type: "RECURSO_EXTRAORDINARIO",
    displayName: "Recurso Extraordinário",
    shortName: "RE",
    category: "RECURSAL",
    legalBasis: "Art. 1.003, §5º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "landmark",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { repercussaoGeral: true },
    sortOrder: 108,
  },
  {
    type: "CONTRARRAZOES_RE",
    displayName: "Contrarrazões de RE",
    shortName: "C/R RE",
    category: "RECURSAL",
    legalBasis: "Art. 1.030, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "landmark",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 109,
  },
  {
    type: "EMBARGOS_DIVERGENCIA",
    displayName: "Embargos de Divergência",
    shortName: "Emb.Div.",
    category: "RECURSAL",
    legalBasis: "Art. 1.043, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "git-branch",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 110,
  },
  {
    type: "RECURSO_REVISTA",
    displayName: "Recurso de Revista",
    shortName: "RR",
    category: "RECURSAL",
    legalBasis: "Art. 896, CLT",
    defaultDays: 8,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "briefcase",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { trabalhista: true },
    sortOrder: 111,
  },
  {
    type: "RECURSO_ORDINARIO_TRABALHISTA",
    displayName: "Recurso Ordinário Trabalhista",
    shortName: "RO Trab.",
    category: "RECURSAL",
    legalBasis: "Art. 895, CLT",
    defaultDays: 8,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "briefcase",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { trabalhista: true },
    sortOrder: 112,
  },
  {
    type: "AGRAVO_PETICAO",
    displayName: "Agravo de Petição",
    shortName: "Ag.Pet.",
    category: "RECURSAL",
    legalBasis: "Art. 897, CLT",
    defaultDays: 8,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "briefcase",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { trabalhista: true, execucao: true },
    sortOrder: 113,
  },
  {
    type: "RECLAMACAO",
    displayName: "Reclamação",
    shortName: "Reclam.",
    category: "RECURSAL",
    legalBasis: "Art. 988, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#7C3AED",
    icon: "alert-triangle",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 114,
  },

  // ── FATAIS E PEREMPTÓRIOS ──────────────────────────────
  {
    type: "PRAZO_FATAL",
    displayName: "Prazo Fatal (Genérico)",
    shortName: "Fatal",
    category: "FATAL_PEREMPTORIO",
    legalBasis: null,
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#991B1B",
    icon: "alert-octagon",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 200,
  },
  {
    type: "ACAO_RESCISORIA",
    displayName: "Ação Rescisória",
    shortName: "Resc.",
    category: "FATAL_PEREMPTORIO",
    legalBasis: "Art. 975, CPC",
    defaultDays: 730,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#991B1B",
    icon: "file-x",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { doisAnos: true, transitoEmJulgado: true },
    sortOrder: 201,
  },
  {
    type: "MANDADO_SEGURANCA",
    displayName: "Mandado de Segurança",
    shortName: "MS",
    category: "FATAL_PEREMPTORIO",
    legalBasis: "Art. 23, Lei 12.016/2009",
    defaultDays: 120,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#991B1B",
    icon: "shield-alert",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { decadencial: true, daCienciaDoAto: true },
    sortOrder: 202,
  },
  {
    type: "HABEAS_CORPUS",
    displayName: "Habeas Corpus",
    shortName: "HC",
    category: "FATAL_PEREMPTORIO",
    legalBasis: "Art. 5º, LXVIII, CF",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#991B1B",
    icon: "key",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { semPrazo: true, aQualquerTempo: true },
    sortOrder: 203,
  },

  // ── AUDIÊNCIAS E SESSÕES ───────────────────────────────
  {
    type: "AUDIENCIA_CONCILIACAO",
    displayName: "Audiência de Conciliação/Mediação",
    shortName: "Aud.Conc.",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 334, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#0EA5E9",
    icon: "users",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true, naoDesejaComparecerAte10Dias: true },
    sortOrder: 300,
  },
  {
    type: "AUDIENCIA_INSTRUCAO",
    displayName: "Audiência de Instrução e Julgamento",
    shortName: "AIJ",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 358, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#0EA5E9",
    icon: "mic",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true },
    sortOrder: 301,
  },
  {
    type: "AUDIENCIA_SANEAMENTO",
    displayName: "Audiência de Saneamento",
    shortName: "Aud.San.",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 357, §3º, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#0EA5E9",
    icon: "clipboard-check",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true },
    sortOrder: 302,
  },
  {
    type: "SUSTENTACAO_ORAL",
    displayName: "Sustentação Oral",
    shortName: "Sust.Oral",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 937, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#0EA5E9",
    icon: "presentation",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true, inscricaoPrevia: true },
    sortOrder: 303,
  },
  {
    type: "ASSEMBLEIA_CREDORES",
    displayName: "Assembleia Geral de Credores",
    shortName: "AGC",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 36, Lei 11.101/2005",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#0EA5E9",
    icon: "building-2",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true, rj: true },
    sortOrder: 304,
  },
  {
    type: "MEDIACAO",
    displayName: "Sessão de Mediação",
    shortName: "Mediação",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Lei 13.140/2015",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#0EA5E9",
    icon: "handshake",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true },
    sortOrder: 305,
  },
  {
    type: "DEPOIMENTO_PESSOAL",
    displayName: "Depoimento Pessoal",
    shortName: "Dep.Pess.",
    category: "AUDIENCIA_SESSAO",
    legalBasis: "Art. 385, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#0EA5E9",
    icon: "user-check",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { confissao: true },
    sortOrder: 306,
  },

  // ── RECUPERAÇÃO JUDICIAL (Lei 11.101/2005) ─────────────
  {
    type: "RJ_STAY_PERIOD",
    displayName: "Stay Period (180 dias)",
    shortName: "Stay",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 6º, §4º, Lei 11.101/2005",
    defaultDays: 180,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#059669",
    icon: "pause-circle",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { prorrogavelIgualPeriodo: true },
    sortOrder: 400,
  },
  {
    type: "RJ_APRESENTACAO_PLANO",
    displayName: "Apresentação do Plano de RJ",
    shortName: "Plano RJ",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 53, Lei 11.101/2005",
    defaultDays: 60,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#059669",
    icon: "file-text",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { aPartirDoDespachoProcessamento: true },
    sortOrder: 401,
  },
  {
    type: "RJ_OBJECAO_PLANO",
    displayName: "Objeção ao Plano de RJ",
    shortName: "Objeção",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 55, §3º, Lei 11.101/2005",
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#059669",
    icon: "file-warning",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { aPartirPublicacaoEditalPlano: true },
    sortOrder: 402,
  },
  {
    type: "RJ_HABILITACAO_CREDITO",
    displayName: "Habilitação de Crédito (RJ)",
    shortName: "Hab.Créd.",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 7º, §1º, Lei 11.101/2005",
    defaultDays: 15,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#059669",
    icon: "clipboard-plus",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { aPartirPublicacaoEdital: true },
    sortOrder: 403,
  },
  {
    type: "RJ_IMPUGNACAO_CREDITO",
    displayName: "Impugnação de Crédito (RJ)",
    shortName: "Imp.Créd.",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 8º, Lei 11.101/2005",
    defaultDays: 10,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#059669",
    icon: "clipboard-x",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { aPartirPublicacaoQuadro: true },
    sortOrder: 404,
  },
  {
    type: "RJ_DIVERGENCIA_CREDITO",
    displayName: "Divergência de Crédito (RJ)",
    shortName: "Div.Créd.",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 8º, Lei 11.101/2005",
    defaultDays: 10,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#059669",
    icon: "git-compare",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 405,
  },
  {
    type: "RJ_PRESTACAO_CONTAS_AJ",
    displayName: "Prestação de Contas do AJ",
    shortName: "Prest.AJ",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 22, Lei 11.101/2005",
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#059669",
    icon: "receipt",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { mensal: true },
    sortOrder: 406,
  },
  {
    type: "RJ_CUMPRIMENTO_PLANO",
    displayName: "Cumprimento do Plano de RJ (2 anos)",
    shortName: "Cumpr.Plano",
    category: "RECUPERACAO_JUDICIAL",
    legalBasis: "Art. 61, Lei 11.101/2005",
    defaultDays: 730,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "MEDIA",
    color: "#059669",
    icon: "check-circle",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { doisAnosAposConcessao: true },
    sortOrder: 407,
  },

  // ── EXECUÇÃO E CUMPRIMENTO ─────────────────────────────
  {
    type: "PAGAMENTO_VOLUNTARIO",
    displayName: "Pagamento Voluntário (15 dias)",
    shortName: "Pag.Vol.",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 523, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#16A34A",
    icon: "banknote",
    doubleForPublicEntity: true,
    doubleForDefensoria: false,
    specialRules: { multa10Porcento: true, honorarios10Porcento: true },
    sortOrder: 500,
  },
  {
    type: "PENHORA",
    displayName: "Penhora",
    shortName: "Penhora",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 831, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#16A34A",
    icon: "lock",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 501,
  },
  {
    type: "ADJUDICACAO",
    displayName: "Adjudicação",
    shortName: "Adjudic.",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 876, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#16A34A",
    icon: "badge-check",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 502,
  },
  {
    type: "DEPOSITO_JUDICIAL",
    displayName: "Depósito Judicial",
    shortName: "Dep.Jud.",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: null,
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#16A34A",
    icon: "piggy-bank",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 503,
  },
  {
    type: "PRESTACAO_CONTAS",
    displayName: "Prestação de Contas",
    shortName: "Prest.Contas",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 550, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#16A34A",
    icon: "receipt",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 504,
  },
  {
    type: "LEILAO",
    displayName: "Leilão Judicial",
    shortName: "Leilão",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 881, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#16A34A",
    icon: "gavel",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixa: true },
    sortOrder: 505,
  },
  {
    type: "HASTA_PUBLICA",
    displayName: "Hasta Pública",
    shortName: "Hasta",
    category: "EXECUCAO_CUMPRIMENTO",
    legalBasis: "Art. 881, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#16A34A",
    icon: "gavel",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixa: true },
    sortOrder: 506,
  },

  // ── ADMINISTRATIVO E DILIGÊNCIAS ───────────────────────
  {
    type: "DILIGENCIA",
    displayName: "Diligência",
    shortName: "Diligência",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "clipboard-list",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 600,
  },
  {
    type: "PROTOCOLO",
    displayName: "Protocolo",
    shortName: "Protocolo",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "file-input",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 601,
  },
  {
    type: "JUNTADA_DOCUMENTO",
    displayName: "Juntada de Documento",
    shortName: "Juntada",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "file-plus",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 602,
  },
  {
    type: "JUNTADA_PROCURACAO",
    displayName: "Juntada de Procuração",
    shortName: "Junt.Proc.",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 104, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#6B7280",
    icon: "file-signature",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 603,
  },
  {
    type: "SUBSTABELECIMENTO",
    displayName: "Substabelecimento",
    shortName: "Substab.",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "user-plus",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 604,
  },
  {
    type: "CARGA_AUTOS",
    displayName: "Carga/Vista dos Autos",
    shortName: "Carga",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 107, IV, CPC",
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "folder-open",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 605,
  },
  {
    type: "PERICIA",
    displayName: "Perícia",
    shortName: "Perícia",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 465, CPC",
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#6B7280",
    icon: "search",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { dataFixaJuiz: true },
    sortOrder: 606,
  },
  {
    type: "LAUDO_PERICIAL",
    displayName: "Laudo Pericial (manifestação)",
    shortName: "Laudo",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 477, §1º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#6B7280",
    icon: "file-search",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 607,
  },
  {
    type: "QUESITOS",
    displayName: "Quesitos",
    shortName: "Quesitos",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 465, §1º, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#6B7280",
    icon: "help-circle",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 608,
  },
  {
    type: "CUMPRIMENTO_DECISAO",
    displayName: "Cumprimento de Decisão",
    shortName: "Cumpr.Dec.",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#6B7280",
    icon: "check-square",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: null,
    sortOrder: 609,
  },
  {
    type: "EMENDA_INICIAL",
    displayName: "Emenda à Inicial",
    shortName: "Emenda",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: "Art. 321, CPC",
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#6B7280",
    icon: "file-edit",
    doubleForPublicEntity: true,
    doubleForDefensoria: true,
    specialRules: { indeferimentoSeNaoCumprir: true },
    sortOrder: 610,
  },
  {
    type: "COMPLEMENTACAO_CUSTAS",
    displayName: "Complementação de Custas",
    shortName: "Compl.Custas",
    category: "ADMINISTRATIVO_DILIGENCIA",
    legalBasis: null,
    defaultDays: 15,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#6B7280",
    icon: "coins",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 611,
  },

  // ── EXTRAJUDICIAIS E CONTRATUAIS ───────────────────────
  {
    type: "NOTIFICACAO_EXTRAJUDICIAL",
    displayName: "Notificação Extrajudicial",
    shortName: "Not.Extraj.",
    category: "EXTRAJUDICIAL_CONTRATUAL",
    legalBasis: null,
    defaultDays: 10,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#D97706",
    icon: "mail-warning",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 700,
  },
  {
    type: "VENCIMENTO_CONTRATO",
    displayName: "Vencimento de Contrato",
    shortName: "Venc.Contr.",
    category: "EXTRAJUDICIAL_CONTRATUAL",
    legalBasis: null,
    defaultDays: 0,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#D97706",
    icon: "calendar-clock",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 701,
  },
  {
    type: "PRAZO_REGULATORIO",
    displayName: "Prazo Regulatório",
    shortName: "Regulatório",
    category: "EXTRAJUDICIAL_CONTRATUAL",
    legalBasis: null,
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#D97706",
    icon: "building",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 702,
  },
  {
    type: "PRAZO_ADMINISTRATIVO",
    displayName: "Prazo Administrativo",
    shortName: "Admin.",
    category: "EXTRAJUDICIAL_CONTRATUAL",
    legalBasis: null,
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#D97706",
    icon: "building-2",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 703,
  },

  // ── TRIBUTÁRIOS ────────────────────────────────────────
  {
    type: "IMPUGNACAO_AUTO_INFRACAO",
    displayName: "Impugnação de Auto de Infração",
    shortName: "Imp.AI",
    category: "TRIBUTARIO",
    legalBasis: "Art. 15, Dec. 70.235/1972",
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#B91C1C",
    icon: "file-x-2",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { processoAdminFiscal: true },
    sortOrder: 800,
  },
  {
    type: "RECURSO_ADMINISTRATIVO_FISCAL",
    displayName: "Recurso Administrativo Fiscal",
    shortName: "Rec.Fiscal",
    category: "TRIBUTARIO",
    legalBasis: "Art. 33, Dec. 70.235/1972",
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: false,
    isFatal: true,
    defaultPriority: "CRITICA",
    color: "#B91C1C",
    icon: "arrow-up-square",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: { processoAdminFiscal: true },
    sortOrder: 801,
  },
  {
    type: "PARCELAMENTO",
    displayName: "Parcelamento Tributário",
    shortName: "Parcel.",
    category: "TRIBUTARIO",
    legalBasis: null,
    defaultDays: 30,
    countingType: "DIAS_CORRIDOS",
    isExtendable: true,
    isFatal: true,
    defaultPriority: "ALTA",
    color: "#B91C1C",
    icon: "split",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 802,
  },

  // ── TAREFAS INTERNAS ───────────────────────────────────
  {
    type: "TAREFA_INTERNA",
    displayName: "Tarefa Interna",
    shortName: "Tarefa",
    category: "TAREFA_INTERNA",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#8B5CF6",
    icon: "check-circle",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 900,
  },
  {
    type: "FOLLOW_UP",
    displayName: "Follow-up",
    shortName: "Follow-up",
    category: "TAREFA_INTERNA",
    legalBasis: null,
    defaultDays: 3,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "BAIXA",
    color: "#8B5CF6",
    icon: "repeat",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 901,
  },
  {
    type: "REUNIAO_INTERNA",
    displayName: "Reunião Interna",
    shortName: "Reunião",
    category: "TAREFA_INTERNA",
    legalBasis: null,
    defaultDays: 0,
    countingType: "SEM_PRAZO",
    isExtendable: false,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#8B5CF6",
    icon: "users-2",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 902,
  },
  {
    type: "RETORNO_CLIENTE",
    displayName: "Retorno ao Cliente",
    shortName: "Ret.Cliente",
    category: "TAREFA_INTERNA",
    legalBasis: null,
    defaultDays: 2,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "ALTA",
    color: "#8B5CF6",
    icon: "phone-call",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 903,
  },
  {
    type: "RETORNO_EMAIL",
    displayName: "Retorno de E-mail",
    shortName: "Ret.E-mail",
    category: "TAREFA_INTERNA",
    legalBasis: null,
    defaultDays: 1,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#8B5CF6",
    icon: "mail-check",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 904,
  },
  {
    type: "OUTRO",
    displayName: "Outro",
    shortName: "Outro",
    category: "OUTRO",
    legalBasis: null,
    defaultDays: 5,
    countingType: "DIAS_UTEIS",
    isExtendable: true,
    isFatal: false,
    defaultPriority: "MEDIA",
    color: "#9CA3AF",
    icon: "circle-dot",
    doubleForPublicEntity: false,
    doubleForDefensoria: false,
    specialRules: null,
    sortOrder: 999,
  },
];

// ============================================================
// TRIGGERS: VINCULAÇÃO PEÇA → PRAZO (40+ entries)
// ============================================================
const triggerEntries: TriggerEntry[] = [
  // ── Citação → Prazos de defesa ─────────────────────────
  {
    deadlineType: "CONTESTACAO",
    triggerPieceType: "CITACAO",
    triggerDescription: "Contestação após citação",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 335, CPC — 15 dias úteis",
  },
  {
    deadlineType: "RECONVENCAO",
    triggerPieceType: "CITACAO",
    triggerDescription: "Reconvenção junto com contestação",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 343, CPC — mesmo prazo da contestação",
  },
  {
    deadlineType: "EXCECAO_PRE_EXECUTIVIDADE",
    triggerPieceType: "CITACAO",
    triggerDescription: "Exceção de pré-executividade após citação em execução",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: false,
    notes: "Prazo convencional — jurisprudência aceita a qualquer tempo",
  },

  // ── Sentença → Recursos ────────────────────────────────
  {
    deadlineType: "APELACAO",
    triggerPieceType: "INTIMACAO_SENTENCA",
    triggerDescription: "Apelação contra sentença",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.003, §5º, CPC — 15 dias úteis",
  },
  {
    deadlineType: "EMBARGOS_DECLARACAO",
    triggerPieceType: "INTIMACAO_SENTENCA",
    triggerDescription: "Embargos de declaração da sentença",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 1.023, CPC — 5 dias úteis",
  },
  {
    deadlineType: "CONTRARRAZOES_APELACAO",
    triggerPieceType: "APELACAO_RECEBIDA",
    triggerDescription: "Contrarrazões da apelação da parte contrária",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.010, §1º, CPC — 15 dias úteis",
  },

  // ── Decisão interlocutória → Agravo ────────────────────
  {
    deadlineType: "AGRAVO_INSTRUMENTO",
    triggerPieceType: "INTIMACAO_DECISAO",
    triggerDescription: "Agravo de instrumento contra decisão interlocutória",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.015, CPC — 15 dias úteis",
  },
  {
    deadlineType: "EMBARGOS_DECLARACAO",
    triggerPieceType: "INTIMACAO_DECISAO",
    triggerDescription: "Embargos de declaração da decisão",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 1.023, CPC — 5 dias úteis",
  },
  {
    deadlineType: "CONTRARRAZOES_AGRAVO",
    triggerPieceType: "AGRAVO_RECEBIDO",
    triggerDescription: "Contrarrazões do agravo da parte contrária",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.019, II, CPC — 15 dias úteis",
  },

  // ── Acórdão → Recursos superiores ─────────────────────
  {
    deadlineType: "RECURSO_ESPECIAL",
    triggerPieceType: "INTIMACAO_ACORDAO",
    triggerDescription: "REsp contra acórdão",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.003, §5º, CPC — 15 dias úteis",
  },
  {
    deadlineType: "RECURSO_EXTRAORDINARIO",
    triggerPieceType: "INTIMACAO_ACORDAO",
    triggerDescription: "RE contra acórdão",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 1.003, §5º, CPC — 15 dias úteis",
  },
  {
    deadlineType: "EMBARGOS_DECLARACAO",
    triggerPieceType: "INTIMACAO_ACORDAO",
    triggerDescription: "Embargos de declaração do acórdão",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 1.023, CPC — 5 dias úteis",
  },
  {
    deadlineType: "CONTRARRAZOES_RESP",
    triggerPieceType: "RESP_RECEBIDO",
    triggerDescription: "Contrarrazões do REsp da parte contrária",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.030, CPC — 15 dias úteis",
  },
  {
    deadlineType: "CONTRARRAZOES_RE",
    triggerPieceType: "RE_RECEBIDO",
    triggerDescription: "Contrarrazões do RE da parte contrária",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.030, CPC — 15 dias úteis",
  },

  // ── Decisão monocrática → Agravo interno ───────────────
  {
    deadlineType: "AGRAVO_INTERNO",
    triggerPieceType: "DECISAO_MONOCRATICA",
    triggerDescription: "Agravo interno contra decisão monocrática",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 1.021, CPC — 15 dias úteis",
  },
  {
    deadlineType: "EMBARGOS_DECLARACAO",
    triggerPieceType: "DECISAO_MONOCRATICA",
    triggerDescription: "Embargos de declaração da decisão monocrática",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 1.023, CPC — 5 dias úteis",
  },

  // ── Contestação recebida → Réplica ─────────────────────
  {
    deadlineType: "REPLICA",
    triggerPieceType: "CONTESTACAO_RECEBIDA",
    triggerDescription: "Réplica à contestação",
    targetRole: "AUTOR",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 351, CPC — 15 dias úteis",
  },

  // ── Reconvenção recebida → Contestação à reconvenção ──
  {
    deadlineType: "CONTESTACAO",
    triggerPieceType: "RECONVENCAO_RECEBIDA",
    triggerDescription: "Contestação à reconvenção",
    targetRole: "AUTOR",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 343, §1º, CPC — 15 dias úteis",
  },

  // ── Impugnação recebida → Manifestação ─────────────────
  {
    deadlineType: "MANIFESTACAO",
    triggerPieceType: "IMPUGNACAO_RECEBIDA",
    triggerDescription: "Manifestação sobre impugnação",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Prazo judicial — geralmente 5 ou 15 dias úteis",
  },

  // ── Embargos à execução recebidos ──────────────────────
  {
    deadlineType: "MANIFESTACAO",
    triggerPieceType: "EMBARGOS_EXEC_RECEBIDOS",
    triggerDescription: "Impugnação aos embargos à execução",
    targetRole: "AUTOR",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 920, CPC — 15 dias úteis",
  },

  // ── Cumprimento de sentença → Impugnação ───────────────
  {
    deadlineType: "IMPUGNACAO_CUMPRIMENTO",
    triggerPieceType: "INTIMACAO_CUMPRIMENTO",
    triggerDescription: "Impugnação ao cumprimento de sentença",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 525, CPC — 15 dias úteis após pagamento voluntário",
  },
  {
    deadlineType: "PAGAMENTO_VOLUNTARIO",
    triggerPieceType: "INTIMACAO_CUMPRIMENTO",
    triggerDescription: "Pagamento voluntário (15 dias)",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 523, CPC — multa 10% + honorários 10%",
  },

  // ── Penhora → Embargos de terceiro ─────────────────────
  {
    deadlineType: "EMBARGOS_TERCEIRO",
    triggerPieceType: "INTIMACAO_PENHORA",
    triggerDescription: "Embargos de terceiro contra penhora",
    targetRole: "TERCEIRO",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 675, CPC — 5 dias",
  },
  {
    deadlineType: "EMBARGOS_EXECUCAO",
    triggerPieceType: "INTIMACAO_PENHORA",
    triggerDescription: "Embargos à execução após penhora",
    targetRole: "REU",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 915, CPC — 15 dias úteis",
  },

  // ── Perícia → Manifestações ────────────────────────────
  {
    deadlineType: "QUESITOS",
    triggerPieceType: "INTIMACAO_PERICIA",
    triggerDescription: "Quesitos para a perícia",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 465, §1º, CPC — 15 dias",
  },
  {
    deadlineType: "LAUDO_PERICIAL",
    triggerPieceType: "PERICIA_DESIGNADA",
    triggerDescription: "Manifestação sobre laudo pericial",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 477, §1º, CPC — 15 dias",
  },

  // ── Audiência designada ────────────────────────────────
  {
    deadlineType: "AUDIENCIA_CONCILIACAO",
    triggerPieceType: "AUDIENCIA_DESIGNADA",
    triggerDescription: "Preparação para audiência de conciliação",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 334, CPC",
  },

  // ── RJ: Deferimento → Stay, Plano ─────────────────────
  {
    deadlineType: "RJ_STAY_PERIOD",
    triggerPieceType: "RJ_DEFERIMENTO",
    triggerDescription: "Início do stay period após deferimento da RJ",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 6º, §4º, Lei 11.101/2005 — 180 dias",
  },
  {
    deadlineType: "RJ_APRESENTACAO_PLANO",
    triggerPieceType: "RJ_DEFERIMENTO",
    triggerDescription: "Prazo para apresentação do plano de RJ",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 53, Lei 11.101/2005 — 60 dias",
  },

  // ── RJ: Publicação edital → Habilitação ────────────────
  {
    deadlineType: "RJ_HABILITACAO_CREDITO",
    triggerPieceType: "RJ_PUBLICACAO_EDITAL",
    triggerDescription: "Habilitação de crédito após publicação do edital",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 7º, §1º, Lei 11.101/2005 — 15 dias",
  },

  // ── RJ: Publicação quadro → Impugnação e divergência ──
  {
    deadlineType: "RJ_IMPUGNACAO_CREDITO",
    triggerPieceType: "RJ_PUBLICACAO_QUADRO",
    triggerDescription: "Impugnação de crédito após publicação do QGC",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 8º, Lei 11.101/2005 — 10 dias",
  },
  {
    deadlineType: "RJ_DIVERGENCIA_CREDITO",
    triggerPieceType: "RJ_PUBLICACAO_QUADRO",
    triggerDescription: "Divergência de crédito após publicação do QGC",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 8º, Lei 11.101/2005 — 10 dias",
  },

  // ── RJ: Plano apresentado → Objeção ───────────────────
  {
    deadlineType: "RJ_OBJECAO_PLANO",
    triggerPieceType: "RJ_PLANO_APRESENTADO",
    triggerDescription: "Objeção ao plano de RJ apresentado",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 55, §3º, Lei 11.101/2005 — 30 dias",
  },

  // ── Mandado de Segurança ───────────────────────────────
  {
    deadlineType: "MANDADO_SEGURANCA",
    triggerPieceType: "MS_ATO_COATOR",
    triggerDescription: "MS contra ato coator",
    targetRole: "CLIENTE",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 23, Lei 12.016/2009 — 120 dias corridos (decadencial)",
  },

  // ── Despacho genérico → Cumprimento ────────────────────
  {
    deadlineType: "CUMPRIMENTO_DECISAO",
    triggerPieceType: "INTIMACAO_DESPACHO",
    triggerDescription: "Cumprimento de despacho",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Prazo judicial — verificar no despacho",
  },
  {
    deadlineType: "EMENDA_INICIAL",
    triggerPieceType: "INTIMACAO_DESPACHO",
    triggerDescription: "Emenda à inicial por determinação judicial",
    targetRole: "AUTOR",
    isSuggestion: true,
    isDefault: false,
    notes: "Art. 321, CPC — 15 dias úteis",
  },

  // ── Publicação DJE → Genérico ──────────────────────────
  {
    deadlineType: "MANIFESTACAO",
    triggerPieceType: "PUBLICACAO_DJE",
    triggerDescription: "Manifestação após publicação no DJE",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: false,
    notes: "Verificar tipo de publicação para prazo específico",
  },

  // ── Leilão designado ───────────────────────────────────
  {
    deadlineType: "LEILAO",
    triggerPieceType: "LEILAO_DESIGNADO",
    triggerDescription: "Leilão judicial designado",
    targetRole: "AMBOS",
    isSuggestion: true,
    isDefault: true,
    notes: "Art. 881, CPC — data fixa",
  },
];

async function main() {
  console.log("📋 Seeding DeadlineTypeCatalog and DeadlinePieceTrigger...\n");

  // Clean existing data
  await prisma.deadlinePieceTrigger.deleteMany();
  await prisma.deadlineTypeCatalog.deleteMany();
  console.log("🗑️  Cleaned existing catalog and trigger data\n");

  // ── Insert catalog entries ──
  let catalogCount = 0;
  const catalogMap: Record<string, string> = {};

  for (const entry of catalogEntries) {
    const created = await prisma.deadlineTypeCatalog.create({
      data: {
        type: entry.type,
        displayName: entry.displayName,
        shortName: entry.shortName,
        category: entry.category,
        legalBasis: entry.legalBasis,
        defaultDays: entry.defaultDays,
        countingType: entry.countingType,
        isExtendable: entry.isExtendable,
        isFatal: entry.isFatal,
        defaultPriority: entry.defaultPriority,
        color: entry.color,
        icon: entry.icon,
        doubleForPublicEntity: entry.doubleForPublicEntity,
        doubleForDefensoria: entry.doubleForDefensoria,
        specialRules: (entry.specialRules as any) ?? undefined,
        isActive: true,
        sortOrder: entry.sortOrder,
      },
    });
    catalogMap[entry.type] = created.id;
    catalogCount++;
  }
  console.log(`✅ Created ${catalogCount} DeadlineTypeCatalog entries`);

  // ── Insert trigger entries ──
  let triggerCount = 0;

  for (const entry of triggerEntries) {
    const catalogId = catalogMap[entry.deadlineType];
    if (!catalogId) {
      console.warn(`⚠️  Skipping trigger: no catalog entry for ${entry.deadlineType}`);
      continue;
    }

    await prisma.deadlinePieceTrigger.create({
      data: {
        deadlineTypeId: catalogId,
        deadlineType: entry.deadlineType,
        triggerPieceType: entry.triggerPieceType,
        triggerDescription: entry.triggerDescription,
        targetRole: entry.targetRole,
        isSuggestion: entry.isSuggestion,
        isDefault: entry.isDefault,
        notes: entry.notes,
      },
    });
    triggerCount++;
  }
  console.log(`✅ Created ${triggerCount} DeadlinePieceTrigger entries`);

  // ── Summary ──
  console.log("\n📊 Seed Summary:");
  console.log(`   Categories: ${new Set(catalogEntries.map((e) => e.category)).size}`);
  console.log(`   Total types: ${catalogCount}`);
  console.log(`   Total triggers: ${triggerCount}`);
  console.log(`   Piece types covered: ${new Set(triggerEntries.map((e) => e.triggerPieceType)).size}`);
  console.log("\n🎉 Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
