import { PrismaClient } from "@prisma/client"

const db = new PrismaClient({
  datasourceUrl: process.env.DIRECT_URL || process.env.DATABASE_URL,
})

interface CatalogSeed {
  codigo: string
  nome: string
  descricao: string
  dias: number
  contagem_tipo: string
  tipo_prazo: string
  categoria: string
  subcategoria?: string
  artigo: string
  lei: string
  paragrafos?: string
  admite_dobra: boolean
  excecao_dobra?: string
  admite_litisconsorcio: boolean
  excecao_litisconsorcio?: string
  efeito_nao_cumprimento?: string
  efeito_recursal?: string
  termo_inicial: string
  observacoes?: string
  jurisprudencia?: string
  prazo_resposta_dias?: number
  prazo_resposta_ref?: string
}

// ===========================================================================
//  CATALOGO COMPLETO DE PRAZOS PROCESSUAIS E GERENCIAIS
//  Para uso no sistema JRCLaw — seed da tabela DeadlineCatalog
// ===========================================================================

const CATALOG_ENTRIES: CatalogSeed[] = [
  // =========================================================================
  //  CPC GERAL — Prazos de resposta, manifestacoes e atos da parte
  // =========================================================================
  {
    codigo: "CPC-001",
    nome: "Contestacao",
    descricao: "Prazo para o reu apresentar contestacao nos autos, sob pena de revelia e presuncao de veracidade dos fatos alegados pelo autor.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 335",
    lei: "CPC/2015",
    paragrafos: "Caput e §§1o e 2o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Revelia — presuncao relativa de veracidade dos fatos (Art. 344 CPC)",
    termo_inicial: "Da audiencia de conciliacao/mediacao frustrada ou do protocolo da peticao de nao comparecimento, ou da juntada do mandado de citacao quando nao designada audiencia",
    observacoes: "Prazo em dobro para litisconsortes com procuradores diferentes de escritorios distintos (Art. 229 CPC). Fazenda Publica e Defensoria possuem prazo em dobro (Arts. 183 e 186 CPC). Se houver audiencia de conciliacao, o prazo conta do nao acordo ou nao comparecimento do autor.",
    jurisprudencia: "STJ, REsp 1.738.756/RJ — O prazo de contestacao conta da audiencia de conciliacao frustrada, nao da data da intimacao da decisao que a designou.",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "CPC-002",
  },
  {
    codigo: "CPC-002",
    nome: "Replica (Impugnacao a contestacao)",
    descricao: "Prazo para o autor se manifestar sobre a contestacao apresentada pelo reu, impugnando fatos novos, preliminares e documentos.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 351",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — presume-se que o autor concordou com os fatos e documentos nao impugnados",
    termo_inicial: "Da intimacao para replica",
    observacoes: "O prazo e de 15 dias uteis. Se a contestacao trouxer preliminares (Art. 337 CPC), o juiz abrira prazo para replica obrigatoriamente. Se trouxer apenas fatos novos, o juiz podera ou nao abrir vista.",
  },
  {
    codigo: "CPC-003",
    nome: "Embargos de Declaracao",
    descricao: "Prazo para oposicao de embargos de declaracao contra qualquer decisao judicial que contenha obscuridade, contradicao, omissao ou erro material.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RECURSO",
    artigo: "Art. 1.023",
    lei: "CPC/2015",
    admite_dobra: false,
    excecao_dobra: "Embargos de declaracao nao admitem prazo em dobro, exceto para Fazenda Publica e Defensoria Publica (Arts. 183 e 186 CPC)",
    admite_litisconsorcio: false,
    excecao_litisconsorcio: "Nao se aplica dobra por litisconsorcio aos embargos de declaracao",
    efeito_nao_cumprimento: "Preclusao temporal — impossibilidade de corrigir obscuridade, contradicao ou omissao por esta via",
    efeito_recursal: "Interrompe o prazo para interposicao de outros recursos (Art. 1.026 CPC)",
    termo_inicial: "Da intimacao/publicacao da decisao embargada",
    observacoes: "Os embargos INTERROMPEM o prazo dos demais recursos (Art. 1.026 CPC), ou seja, o prazo recomeça do zero. Podem ter efeitos infringentes excepcionalmente. Cuidado: embargos manifestamente protelatórios sujeitam a parte a multa de ate 2% do valor da causa (Art. 1.026 §2 CPC).",
    jurisprudencia: "STJ, Sumula 418 — E inadmissivel o recurso especial interposto antes da publicacao do acordao dos embargos de declaracao, sem posterior ratificacao.",
  },
  {
    codigo: "CPC-004",
    nome: "Impugnacao ao cumprimento de sentenca",
    descricao: "Prazo para o executado impugnar o cumprimento de sentenca, alegando as materias previstas no Art. 525 §1 do CPC.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 525",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — impossibilidade de alegar as materias proprias da impugnacao, salvo materias de ordem publica",
    termo_inicial: "Da intimacao para cumprimento voluntario (apos transcorrido o prazo de 15 dias para pagamento do Art. 523)",
    observacoes: "O prazo de impugnacao so comeca a correr apos o termino do prazo de 15 dias para pagamento voluntario (Art. 523 CPC). A impugnacao nao tem efeito suspensivo automatico — deve ser requerido e deferido pelo juiz (Art. 525 §6 CPC).",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "Manifestacao do exequente",
  },
  {
    codigo: "CPC-005",
    nome: "Embargos a execucao",
    descricao: "Prazo para o executado opor embargos a execucao de titulo extrajudicial.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 915",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — o executado nao podera mais discutir as materias proprias dos embargos (Art. 917 CPC)",
    termo_inicial: "Da juntada aos autos do mandado de citacao cumprido ou, quando a citacao for por correio, da juntada do aviso de recebimento",
    observacoes: "Independem de penhora, deposito ou caucao (Art. 914 CPC). Nao tem efeito suspensivo automatico — deve ser requerido (Art. 919 §1 CPC). Podem ser opostos antes da penhora.",
  },
  {
    codigo: "CPC-006",
    nome: "Manifestacao sobre documentos novos",
    descricao: "Prazo para a parte contraria se manifestar sobre documentos juntados pela outra parte.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "MANIFESTACAO",
    artigo: "Art. 437",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Presuncao de concordancia com os documentos juntados",
    termo_inicial: "Da intimacao para manifestacao sobre os documentos",
    observacoes: "Prazo decorrente do contraditorio sobre documentos novos. O juiz pode fixar prazo diverso.",
  },
  {
    codigo: "CPC-007",
    nome: "Arguicao de incompetencia relativa",
    descricao: "Prazo para o reu arguir incompetencia relativa do juizo, como preliminar de contestacao.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 64",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Prorrogacao da competencia — o juizo inicialmente incompetente torna-se competente (Art. 65 CPC)",
    termo_inicial: "Mesmo prazo da contestacao — da audiencia de conciliacao frustrada ou da juntada do mandado de citacao",
    observacoes: "No CPC/2015, a arguicao de incompetencia relativa e feita como preliminar de contestacao, nao mais por excecao em apartado. A incompetencia absoluta pode ser arguida a qualquer tempo.",
  },
  {
    codigo: "CPC-008",
    nome: "Reconvencao",
    descricao: "Prazo para o reu apresentar reconvencao (pedido contraposto ao do autor), na mesma peca da contestacao.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 343",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — impossibilidade de deduzir pedido reconvencional naquele processo",
    termo_inicial: "Mesmo prazo da contestacao (Art. 335 CPC)",
    observacoes: "No CPC/2015, a reconvencao e apresentada na mesma peca da contestacao. Pode ser proposta mesmo na ausencia de contestacao. O autor sera intimado para apresentar resposta a reconvencao em 15 dias.",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "Resposta do autor a reconvencao",
  },
  {
    codigo: "CPC-009",
    nome: "Agravo interno",
    descricao: "Prazo para interposicao de agravo interno contra decisao monocratica do relator.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.021",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado da decisao monocratica",
    efeito_recursal: "Sem efeito suspensivo automatico, salvo decisao do relator",
    termo_inicial: "Da intimacao/publicacao da decisao monocratica do relator",
    observacoes: "O agravo interno e julgado pelo orgao colegiado competente. Se declarado manifestamente inadmissivel ou improcedente por unanimidade, a parte agravante sera condenada a pagar multa de 1% a 5% do valor da causa (Art. 1.021 §4 CPC).",
  },
  {
    codigo: "CPC-010",
    nome: "Contrarrazoes de agravo interno",
    descricao: "Prazo para a parte agravada apresentar contrarrazoes ao agravo interno.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 1.021",
    lei: "CPC/2015",
    paragrafos: "§2o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar",
    termo_inicial: "Da intimacao para contrarrazoes",
    observacoes: "O relator devera intimar o agravado para contrarrazoes antes de submeter o agravo ao colegiado.",
  },
  {
    codigo: "CPC-011",
    nome: "Especificacao de provas",
    descricao: "Prazo para as partes especificarem as provas que pretendem produzir, indicando sua pertinencia.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 357",
    lei: "CPC/2015",
    paragrafos: "§4o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — presume-se desinteresse na producao de provas",
    termo_inicial: "Da intimacao da decisao de saneamento que determinar a especificacao de provas",
    observacoes: "O juiz pode fixar prazo diverso. Deve-se justificar a pertinencia e a necessidade de cada prova requerida.",
  },
  {
    codigo: "CPC-012",
    nome: "Memoriais (alegacoes finais escritas)",
    descricao: "Prazo para as partes apresentarem memoriais (alegacoes finais escritas) apos a instrucao processual.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 364",
    lei: "CPC/2015",
    paragrafos: "§2o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — o juiz sentenciara sem as alegacoes finais da parte omissa",
    termo_inicial: "Da intimacao para apresentacao de memoriais, em prazo sucessivo, iniciando pelo autor",
    observacoes: "Os memoriais substituem os debates orais quando o juiz julgar a causa complexa. Os prazos sao sucessivos: primeiro o autor, depois o reu.",
  },
  {
    codigo: "CPC-013",
    nome: "Quesitos para perito",
    descricao: "Prazo para as partes apresentarem quesitos ao perito e indicarem assistente tecnico.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 465",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao da formulacao de quesitos e indicacao de assistente tecnico",
    termo_inicial: "Da intimacao da decisao que deferir a prova pericial",
    observacoes: "A parte pode formular quesitos suplementares durante a diligencia (Art. 469 CPC). O assistente tecnico pode apresentar parecer divergente (Art. 477 §1 CPC).",
  },
  {
    codigo: "CPC-014",
    nome: "Impugnacao aos calculos do credor",
    descricao: "Prazo para o executado impugnar os calculos apresentados pelo credor no cumprimento de sentenca.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 525",
    lei: "CPC/2015",
    paragrafos: "§4o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Presuncao de concordancia com os calculos apresentados",
    termo_inicial: "Da intimacao dos calculos do credor ou do laudo do contador judicial",
    observacoes: "A impugnacao deve apontar especificamente os erros nos calculos. Calculos homologados nao podem ser revistos, salvo erro material.",
  },
  {
    codigo: "CPC-015",
    nome: "Pagamento voluntario no cumprimento de sentenca",
    descricao: "Prazo para pagamento voluntario no cumprimento de sentenca, sob pena de multa de 10% e honorarios de 10%.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 523",
    lei: "CPC/2015",
    admite_dobra: false,
    excecao_dobra: "Prazo de pagamento nao admite dobra — e prazo para cumprimento de obrigacao",
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Acrescimo de multa de 10% e honorarios advocaticios de 10% sobre o valor do debito (Art. 523 §1 CPC)",
    termo_inicial: "Da intimacao do devedor para pagamento, pessoal ou por advogado",
    observacoes: "O devedor pode efetuar pagamento parcial, caso em que a multa e honorarios incidirao apenas sobre o restante. O pagamento deve incluir custas e honorarios ja fixados.",
    jurisprudencia: "STJ, Tema 961 — A multa do Art. 523 e devida mesmo quando o executado discute o valor por impugnacao.",
  },
  {
    codigo: "CPC-016",
    nome: "Nomeacao de bens a penhora",
    descricao: "Prazo para o executado nomear bens livres e desembaracados para penhora na execucao de titulo extrajudicial.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 829",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "O juiz determinara a penhora de bens pelo oficial de justica ou por meio eletronico (SISBAJUD/RENAJUD/INFOJUD)",
    termo_inicial: "Da juntada do mandado de citacao na execucao de titulo extrajudicial",
    observacoes: "O executado deve observar a ordem de preferencia do Art. 835 CPC. Dinheiro e aplicacoes financeiras tem prioridade.",
  },
  {
    codigo: "CPC-017",
    nome: "Manifestacao generica (5 dias)",
    descricao: "Prazo generico de 5 dias para manifestacao, quando o juiz intima a parte sem fixar prazo especifico.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "MANIFESTACAO",
    artigo: "Art. 218",
    lei: "CPC/2015",
    paragrafos: "§3o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao temporal",
    termo_inicial: "Da intimacao da parte",
    observacoes: "Quando a lei ou o juiz nao fixarem prazo, as intimacoes serao cumpridas em 5 dias uteis (Art. 218 §3 CPC). E o prazo subsidiario do CPC.",
  },
  {
    codigo: "CPC-018",
    nome: "Emenda da petição inicial",
    descricao: "Prazo para o autor emendar a peticao inicial, corrigindo os vicios apontados pelo juiz, sob pena de indeferimento.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 321",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Indeferimento da peticao inicial (Art. 321, paragrafo unico, CPC) — extincao sem resolucao do merito",
    termo_inicial: "Da intimacao da decisao que determinar a emenda",
    observacoes: "O juiz deve indicar com precisao os pontos que devem ser corrigidos ou completados. A emenda pode incluir documentos faltantes, adequacao do valor da causa, regularizacao da representacao processual, etc.",
  },
  {
    codigo: "CPC-019",
    nome: "Indicacao de assistente tecnico",
    descricao: "Prazo para as partes indicarem assistente tecnico para acompanhar a pericia.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 465",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao da indicacao de assistente tecnico",
    termo_inicial: "Da intimacao da decisao que deferir a prova pericial",
    observacoes: "A indicacao do assistente tecnico e feita no mesmo prazo da apresentacao dos quesitos. O assistente tecnico tem direito a acompanhar a pericia e apresentar parecer divergente.",
  },
  {
    codigo: "CPC-020",
    nome: "Cumprimento de decisao interlocutoria generica",
    descricao: "Prazo generico para cumprimento de decisao interlocutoria quando o juiz nao fixa prazo especifico.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "MANIFESTACAO",
    artigo: "Art. 218",
    lei: "CPC/2015",
    paragrafos: "§3o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao ou aplicacao de sancao processual conforme a natureza da determinacao",
    termo_inicial: "Da intimacao da decisao",
    observacoes: "Aplica-se o prazo subsidiario do Art. 218 §3 CPC quando a decisao nao fixa prazo especifico para cumprimento.",
  },
  {
    codigo: "CPC-021",
    nome: "Impugnacao ao valor da causa",
    descricao: "Prazo para o reu impugnar o valor da causa atribuido pelo autor.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 293",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — o valor da causa fixado pelo autor torna-se definitivo",
    termo_inicial: "Mesmo prazo da contestacao — deve ser arguida como preliminar (Art. 337, III, CPC)",
    observacoes: "No CPC/2015, a impugnacao ao valor da causa e alegada como preliminar de contestacao, nao mais em peca apartada.",
  },
  {
    codigo: "CPC-022",
    nome: "Contradita de testemunha",
    descricao: "Prazo para arguir contradicao de testemunha — deve ser feita na audiencia, antes do inicio do depoimento.",
    dias: 0,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 457",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao — a testemunha sera ouvida sem restricoes",
    termo_inicial: "Na audiencia de instrucao, antes do inicio do depoimento da testemunha",
    observacoes: "A contradita deve ser arguida oralmente na audiencia. A prova da suspeicao ou impedimento pode ser feita por documentos ou testemunhas (ate 3).",
  },
  {
    codigo: "CPC-023",
    nome: "Manifestacao sobre laudo pericial",
    descricao: "Prazo para as partes se manifestarem sobre o laudo pericial, podendo apresentar quesitos complementares.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "INSTRUCAO",
    artigo: "Art. 477",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao da impugnacao ao laudo e de quesitos complementares",
    termo_inicial: "Da intimacao da juntada do laudo pericial aos autos",
    observacoes: "Os assistentes tecnicos apresentarao seus pareceres no mesmo prazo. Havendo quesitos complementares, o perito tera 15 dias para responde-los (Art. 477 §2 CPC).",
  },
  {
    codigo: "CPC-024",
    nome: "Chamamento ao processo — citacao",
    descricao: "Prazo para o reu requerer o chamamento ao processo de terceiros coobrigados.",
    dias: 30,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "INTERVENCAO",
    artigo: "Art. 131",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Se nao providenciada a citacao do chamado no prazo, o chamamento perde eficacia",
    termo_inicial: "Da decisao que deferir o chamamento ao processo",
    observacoes: "O chamamento ao processo e cabivel nas hipoteses do Art. 130 CPC. O chamado torna-se litisconsorte passivo.",
  },
  {
    codigo: "CPC-025",
    nome: "Denuncia da lide — citacao",
    descricao: "Prazo para o denunciante providenciar a citacao do denunciado na denuncia da lide.",
    dias: 30,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "INTERVENCAO",
    artigo: "Art. 126",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Perda da denuncia da lide — a parte mantem direito de regresso em acao autonoma",
    termo_inicial: "Da decisao que deferir a denuncia da lide",
    observacoes: "Se o denunciante for o autor, a denuncia sera feita na peticao inicial. Se for o reu, sera feita na contestacao. O denunciado sera citado e tera 15 dias para contestar.",
  },

  // =========================================================================
  //  CPC RECURSOS — Prazos recursais
  // =========================================================================
  {
    codigo: "CPC-REC-001",
    nome: "Apelacao",
    descricao: "Prazo para interposicao de recurso de apelacao contra sentenca de primeiro grau.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.009",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado da sentenca",
    efeito_recursal: "Efeito devolutivo e, em regra, efeito suspensivo (Art. 1.012 CPC). Excecoes ao suspensivo: Art. 1.012 §1 CPC",
    termo_inicial: "Da intimacao da sentenca ou da data da audiencia em que a sentenca foi proferida",
    observacoes: "A apelacao devolve ao tribunal o conhecimento da materia impugnada. Questoes decididas em interlocutorias nao impugnaveis por agravo de instrumento podem ser suscitadas em preliminar de apelacao (Art. 1.009 §1 CPC).",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "CPC-REC-002",
  },
  {
    codigo: "CPC-REC-002",
    nome: "Contrarrazoes de apelacao",
    descricao: "Prazo para o apelado apresentar contrarrazoes ao recurso de apelacao.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 1.010",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar a apelacao",
    termo_inicial: "Da intimacao para contrarrazoes",
    observacoes: "O apelado pode, nas contrarrazoes, impugnar a admissibilidade do recurso e suscitar questoes resolvidas em interlocutorias nao impugnaveis (Art. 1.009 §1 CPC).",
  },
  {
    codigo: "CPC-REC-003",
    nome: "Agravo de instrumento",
    descricao: "Prazo para interposicao de agravo de instrumento contra decisoes interlocutorias impugnaveis.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.015",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao da decisao interlocutoria (se for hipotese taxativa do Art. 1.015, a questao nao podera ser suscitada em apelacao)",
    efeito_recursal: "Sem efeito suspensivo automatico — pode ser requerido ao relator (Art. 1.019, I, CPC)",
    termo_inicial: "Da intimacao da decisao interlocutoria impugnavel",
    observacoes: "O rol do Art. 1.015 CPC e de taxatividade mitigada (STJ, Tema 988). Hipoteses: tutelas provisorias, merito, rejeicao de convencao de arbitragem, incidente de desconsideracao, rejeicao de gratuidade, entre outras. Deve ser instruido com copias obrigatorias (Art. 1.017 CPC).",
    jurisprudencia: "STJ, Tema 988 (REsp 1.696.396/MT) — O rol do Art. 1.015 CPC e de taxatividade mitigada, admitindo agravo de instrumento em situacoes de urgencia.",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "CPC-REC-004",
  },
  {
    codigo: "CPC-REC-004",
    nome: "Contrarrazoes de agravo de instrumento",
    descricao: "Prazo para o agravado apresentar contrarrazoes ao agravo de instrumento.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 1.019",
    lei: "CPC/2015",
    paragrafos: "§2o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar",
    termo_inicial: "Da intimacao do agravado pelo relator",
    observacoes: "O relator devera intimar o agravado para contrarrazoes e, conforme o caso, intimar o MP.",
  },
  {
    codigo: "CPC-REC-005",
    nome: "Recurso especial",
    descricao: "Prazo para interposicao de recurso especial ao STJ contra acordao que contrarie lei federal ou diverga de outro tribunal.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.029",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado do acordao",
    efeito_recursal: "Sem efeito suspensivo automatico (Art. 1.029 §5 CPC) — pode ser requerido ao STJ",
    termo_inicial: "Da intimacao/publicacao do acordao recorrido",
    observacoes: "Hipoteses de cabimento: Art. 105, III, CF — a) contrariar tratado ou lei federal; b) julgar valido ato de governo local contestado em face de lei federal; c) der interpretacao divergente. Exige prequestionamento (Sumulas 282 e 356 STF).",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "CPC-REC-006",
  },
  {
    codigo: "CPC-REC-006",
    nome: "Contrarrazoes de recurso especial",
    descricao: "Prazo para a parte recorrida apresentar contrarrazoes ao recurso especial.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 1.030",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar",
    termo_inicial: "Da intimacao para contrarrazoes",
    observacoes: "As contrarrazoes devem impugnar os fundamentos do recurso e, se o caso, defender a manutenção do acordao por outros fundamentos.",
  },
  {
    codigo: "CPC-REC-007",
    nome: "Recurso extraordinario",
    descricao: "Prazo para interposicao de recurso extraordinario ao STF contra acordao que contrarie dispositivo da Constituicao.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.029",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado do acordao",
    efeito_recursal: "Sem efeito suspensivo automatico — pode ser requerido ao STF",
    termo_inicial: "Da intimacao/publicacao do acordao recorrido",
    observacoes: "Hipoteses: Art. 102, III, CF — a) contrariar dispositivo da CF; b) declarar inconstitucionalidade de tratado; c) julgar valida lei local contestada em face da CF; d) julgar valida lei local contestada em face de lei federal. Exige repercussao geral (Art. 1.035 CPC).",
    prazo_resposta_dias: 15,
    prazo_resposta_ref: "CPC-REC-008",
  },
  {
    codigo: "CPC-REC-008",
    nome: "Contrarrazoes de recurso extraordinario",
    descricao: "Prazo para a parte recorrida apresentar contrarrazoes ao recurso extraordinario.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 1.030",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar",
    termo_inicial: "Da intimacao para contrarrazoes",
    observacoes: "As contrarrazoes devem demonstrar a ausencia de repercussao geral, inadmissibilidade ou improcedencia do recurso.",
  },
  {
    codigo: "CPC-REC-009",
    nome: "Recurso ordinario constitucional",
    descricao: "Prazo para interposicao de recurso ordinario constitucional ao STJ ou STF.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.027",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado do acordao",
    efeito_recursal: "Efeito devolutivo amplo, similar a apelacao",
    termo_inicial: "Da intimacao/publicacao do acordao recorrido",
    observacoes: "Cabivel: ao STF contra habeas corpus, mandado de seguranca, habeas data e mandado de injuncao decididos em unica instancia pelos Tribunais Superiores (Art. 102, II, CF); ao STJ contra habeas corpus e mandado de seguranca decididos em unica instancia pelos TRFs ou TJs (Art. 105, II, CF).",
  },
  {
    codigo: "CPC-REC-010",
    nome: "Embargos de divergencia",
    descricao: "Prazo para interposicao de embargos de divergencia no STJ ou STF quando houver divergencia entre turmas ou secoes.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.043",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado do acordao embargado",
    efeito_recursal: "Efeito devolutivo restrito a divergencia apontada",
    termo_inicial: "Da intimacao/publicacao do acordao embargado",
    observacoes: "Cabivel quando acordao de orgao fracionario do STJ ou STF divergir de julgamento de qualquer outro orgao do mesmo tribunal. Deve demonstrar a divergencia com precisao.",
  },
  {
    codigo: "CPC-REC-011",
    nome: "Agravo em recurso especial ou extraordinario",
    descricao: "Prazo para interposicao de agravo contra decisao que inadmitir recurso especial ou extraordinario.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 1.042",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado — inadmissao definitiva do recurso especial ou extraordinario",
    efeito_recursal: "Sem efeito suspensivo automatico",
    termo_inicial: "Da intimacao da decisao de inadmissao do recurso especial ou extraordinario pelo tribunal de origem",
    observacoes: "E o recurso cabivel quando o presidente ou vice-presidente do tribunal de origem inadmite o REsp ou RE. Nao cabe quando a inadmissao se fundar em tema repetitivo ou repercussao geral (nesse caso, cabe agravo interno — Art. 1.030 §2 CPC).",
  },
  {
    codigo: "CPC-REC-012",
    nome: "Reclamacao constitucional",
    descricao: "Prazo para ajuizamento de reclamacao constitucional perante o STF ou STJ.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "RECURSAL",
    subcategoria: "RECLAMACAO",
    artigo: "Art. 988",
    lei: "CPC/2015",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha preclusao temporal — cabivel enquanto perdurar a violacao",
    termo_inicial: "Enquanto perdurar a situacao que a enseja — nao ha prazo legal",
    observacoes: "Cabivel para: preservar competencia do tribunal; garantir autoridade de suas decisoes; garantir observancia de enunciado de sumula vinculante, decisao em controle concentrado ou precedente em IRDR/IAC. Nao ha prazo prescricional ou decadencial, mas deve ser ajuizada enquanto util.",
  },
  {
    codigo: "CPC-REC-013",
    nome: "Pedido de efeito suspensivo a recurso especial/extraordinario",
    descricao: "Prazo para requerer efeito suspensivo a recurso especial ou extraordinario ja interposto.",
    dias: 0,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "RECURSAL",
    subcategoria: "INCIDENTE",
    artigo: "Art. 1.029",
    lei: "CPC/2015",
    paragrafos: "§5o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "O recurso segue sem efeito suspensivo",
    termo_inicial: "A qualquer tempo apos a interposicao do recurso especial ou extraordinario",
    observacoes: "O pedido de efeito suspensivo e dirigido ao tribunal superior (STJ ou STF). Pode ser formulado ao presidente/vice do tribunal de origem durante a admissibilidade. Exige perigo de dano grave ou de dificil reparacao.",
  },

  // =========================================================================
  //  CPC EXECUCAO — Prazos especiais de execucao
  // =========================================================================
  {
    codigo: "CPC-EXEC-001",
    nome: "Embargos a execucao fiscal",
    descricao: "Prazo para o executado opor embargos a execucao fiscal, contados da garantia do juizo ou da intimacao da penhora.",
    dias: 30,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO_FISCAL",
    artigo: "Art. 16",
    lei: "Lei 6.830/1980 (LEF)",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — impossibilidade de opor embargos a execucao fiscal",
    termo_inicial: "Da intimacao da penhora ou do deposito (Art. 16, III, LEF). Na pratica, da juntada do mandado de intimacao da penhora",
    observacoes: "Diferentemente dos embargos do CPC, na execucao fiscal o prazo e de 30 dias CORRIDOS. A garantia do juizo e requisito para os embargos, salvo excecao de pre-executividade. O STJ tem admitido embargos sem garantia em situacoes excepcionais.",
    jurisprudencia: "STJ, Sumula 393 — A excecao de pre-executividade e admissivel na execucao fiscal relativamente as materias conheciveis de oficio que nao demandem dilacao probatoria.",
  },
  {
    codigo: "CPC-EXEC-002",
    nome: "Impugnacao ao cumprimento de sentenca contra Fazenda Publica",
    descricao: "Prazo para a Fazenda Publica impugnar o cumprimento de sentenca proferida contra ela.",
    dias: 30,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 535",
    lei: "CPC/2015",
    admite_dobra: false,
    excecao_dobra: "A Fazenda Publica ja possui prazo diferenciado de 30 dias — nao se aplica a dobra do Art. 183",
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — expedição de precatorio ou RPV conforme o caso",
    termo_inicial: "Da intimacao da Fazenda Publica para cumprimento (Art. 535 CPC)",
    observacoes: "A impugnacao da Fazenda Publica tem prazo proprio de 30 dias uteis (nao se confunde com a impugnacao geral de 15 dias do Art. 525). As materias aleganeis sao as do Art. 535 §1 CPC.",
  },
  {
    codigo: "CPC-EXEC-003",
    nome: "Excecao de pre-executividade",
    descricao: "Arguicao de materias de ordem publica na execucao, sem necessidade de garantia do juizo.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Construcao jurisprudencial",
    lei: "CPC/2015 (sem previsao expressa)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha preclusao — pode ser arguida a qualquer tempo, desde que nao exija dilacao probatoria",
    termo_inicial: "A qualquer tempo durante a execucao, enquanto nao encerrada",
    observacoes: "Meio de defesa do executado sem necessidade de penhora ou deposito. Restrita a materias de ordem publica que nao exijam dilacao probatoria: prescricao, decadencia, nulidade do titulo, ilegitimidade de parte, excesso de execucao evidente, etc.",
    jurisprudencia: "STJ, Sumula 393 — A excecao de pre-executividade e admissivel na execucao fiscal relativamente as materias conheciveis de oficio que nao demandem dilacao probatoria.",
  },
  {
    codigo: "CPC-EXEC-004",
    nome: "Embargos de terceiro",
    descricao: "Prazo para o terceiro que sofrer turbacao ou esbulho na posse de seus bens por ato de apreensao judicial opor embargos de terceiro.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 675",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Preclusao — impossibilidade de opor embargos de terceiro apos a arrematacao",
    termo_inicial: "Da turbacao ou esbulho (apreensao judicial do bem); podem ser opostos a qualquer tempo no processo de conhecimento e ate 5 dias apos a adjudicacao, alienacao ou arrematacao na execucao",
    observacoes: "Os embargos de terceiro sao distribuidos por dependencia ao juizo que determinou a constricao. O terceiro deve comprovar a posse ou propriedade do bem. Cabem inclusive preventivamente.",
  },
  {
    codigo: "CPC-EXEC-005",
    nome: "Adjudicacao pelo exequente",
    descricao: "Prazo para o exequente requerer a adjudicacao do bem penhorado antes da alienacao judicial.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "DILATATORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 876",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "O bem sera levado a alienacao judicial (leilao)",
    termo_inicial: "Da intimacao do resultado da avaliacao do bem penhorado",
    observacoes: "A adjudicacao tem preferencia sobre a alienacao judicial. O exequente pode adjudicar o bem pelo valor da avaliacao. Havendo mais de um pretendente, proceder-se-a entre eles a licitacao (Art. 876 §5 CPC).",
  },
  {
    codigo: "CPC-EXEC-006",
    nome: "Prazo para pagamento na execucao de titulo extrajudicial",
    descricao: "Prazo para o executado pagar o debito apos citacao na execucao de titulo extrajudicial.",
    dias: 3,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 829",
    lei: "CPC/2015",
    admite_dobra: false,
    excecao_dobra: "Prazo de pagamento nao admite dobra — e prazo para cumprimento de obrigacao",
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Penhora de bens suficientes para satisfacao do credito",
    termo_inicial: "Da juntada do mandado de citacao na execucao de titulo extrajudicial",
    observacoes: "Apos o decurso do prazo de 3 dias sem pagamento, o oficial de justica procedera a penhora de bens. O executado sera intimado da penhora e tera 15 dias para opor embargos (Art. 915 CPC).",
  },

  // =========================================================================
  //  LEI 11.101/2005 — Recuperacao Judicial e Falencia
  // =========================================================================
  {
    codigo: "RJ-001",
    nome: "Prazo de stay (suspensao das acoes e execucoes)",
    descricao: "Periodo de suspensao de todas as acoes e execucoes contra o devedor em recuperacao judicial (stay period).",
    dias: 180,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "STAY",
    artigo: "Art. 6",
    lei: "Lei 11.101/2005",
    paragrafos: "§4o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Retomada das acoes e execucoes individuais contra o devedor, salvo prorrogacao judicial",
    termo_inicial: "Do deferimento do processamento da recuperacao judicial",
    observacoes: "O prazo de 180 dias pode ser prorrogado pelo juiz, desde que o devedor nao tenha concorrido para a demora. Apos a Lei 14.112/2020, o prazo pode ser prorrogado uma unica vez por igual periodo. Acoes de natureza trabalhista prosseguem na Justica do Trabalho, mas a execucao e suspensa. Execucoes fiscais nao se suspendem.",
    jurisprudencia: "STJ, Tema 987 — O prazo de 180 dias do stay pode ser prorrogado excepcionalmente.",
  },
  {
    codigo: "RJ-002",
    nome: "Apresentacao do plano de recuperacao judicial",
    descricao: "Prazo para o devedor apresentar o plano de recuperacao judicial em juizo.",
    dias: 60,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "PLANO",
    artigo: "Art. 53",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Convolacao da recuperacao judicial em falencia (Art. 73, II, Lei 11.101/2005)",
    termo_inicial: "Da publicacao do despacho que deferir o processamento da recuperacao judicial (Art. 52 Lei 11.101/2005)",
    observacoes: "O plano deve conter: discriminacao dos meios de recuperacao (Art. 50), demonstracao de viabilidade economica, e laudo economico-financeiro e de avaliacao. O prazo pode ser prorrogado pelo juiz, mas a jurisprudencia e restritiva.",
  },
  {
    codigo: "RJ-003",
    nome: "Habilitacao de credito",
    descricao: "Prazo para os credores habilitarem seus creditos perante o administrador judicial na recuperacao judicial ou falencia.",
    dias: 15,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "CREDITO",
    artigo: "Art. 7",
    lei: "Lei 11.101/2005",
    paragrafos: "§1o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Habilitacao retardataria — o credor podera habilitar a qualquer tempo, mas perdera direito a voto na AGC e estara sujeito a custas (Art. 10 §§ Lei 11.101/2005)",
    termo_inicial: "Da publicacao do edital previsto no Art. 52 §1 da Lei 11.101/2005",
    observacoes: "A habilitacao e dirigida ao administrador judicial. Apos o prazo, e possivel a habilitacao retardataria diretamente ao juiz. O credito trabalhista de ate 5 salarios minimos tem prioridade.",
  },
  {
    codigo: "RJ-004",
    nome: "Impugnacao de credito",
    descricao: "Prazo para qualquer credor, devedor ou MP impugnar credito habilitado junto ao administrador judicial.",
    dias: 10,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "CREDITO",
    artigo: "Art. 8",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao — o credito sera consolidado conforme publicado pelo administrador judicial",
    termo_inicial: "Da publicacao do edital com a relacao de credores elaborada pelo administrador judicial (Art. 7 §2)",
    observacoes: "A impugnacao e dirigida ao juiz. O impugnado sera intimado para contestar em 5 dias. Se a materia exigir, o juiz podera designar audiencia de instrucao.",
  },
  {
    codigo: "RJ-005",
    nome: "Objecao ao plano de recuperacao judicial",
    descricao: "Prazo para qualquer credor apresentar objecao ao plano de recuperacao judicial publicado.",
    dias: 30,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "PLANO",
    artigo: "Art. 55",
    lei: "Lei 11.101/2005",
    paragrafos: "§3o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Se nenhum credor apresentar objecao, o juiz homologa o plano sem necessidade de AGC (Art. 58 Lei 11.101/2005)",
    termo_inicial: "Da publicacao da relacao de credores pelo administrador judicial (Art. 7 §2 Lei 11.101/2005)",
    observacoes: "A objecao de qualquer credor obriga a convocacao da assembleia geral de credores (AGC) para deliberar sobre o plano. Se nao houver objecao, o plano e homologado pelo juiz sem AGC.",
  },
  {
    codigo: "RJ-006",
    nome: "Voto em assembleia geral de credores (AGC)",
    descricao: "Comparecimento e voto na assembleia geral de credores para deliberacao sobre o plano de recuperacao judicial.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "ASSEMBLEIA",
    artigo: "Art. 36",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Ausencia do credor — voto nao computado. Se o credor for favoravel, e como se aderisse ao plano",
    termo_inicial: "Na data designada para a assembleia geral de credores",
    observacoes: "A convocacao da AGC deve ser publicada com antecedencia minima de 15 dias. O credor pode se fazer representar por procurador com poderes especiais. A aprovacao do plano exige: maioria simples dos presentes na classe I (trabalhistas); credores que representem mais de 50% do total dos creditos nas classes II e III; e maioria das cabecas nas classes II e III.",
  },
  {
    codigo: "RJ-007",
    nome: "Prazo de cumprimento do plano de recuperacao judicial",
    descricao: "Periodo durante o qual o devedor deve cumprir o plano de recuperacao judicial aprovado, sob supervisao judicial.",
    dias: 730,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "CUMPRIMENTO",
    artigo: "Art. 61",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Convolacao em falencia se houver descumprimento durante os 2 anos (Art. 73, IV, Lei 11.101/2005)",
    termo_inicial: "Da concessao da recuperacao judicial (decisao que homologa o plano — Art. 58 Lei 11.101/2005)",
    observacoes: "O periodo de supervisao judicial (2 anos) e contado da concessao da RJ, nao do deferimento do processamento. Apos 2 anos, se cumpridas as obrigacoes do plano vencidas no periodo, o juiz decreta o encerramento da RJ. O descumprimento enseja convolacao em falencia.",
  },
  {
    codigo: "RJ-008",
    nome: "Publicacao do edital de deferimento do processamento",
    descricao: "Prazo para publicacao do edital de deferimento do processamento da recuperacao judicial.",
    dias: 5,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "AUXILIAR",
    subcategoria: "EDITAL",
    artigo: "Art. 52",
    lei: "Lei 11.101/2005",
    paragrafos: "§1o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Atraso na publicacao — prazo do juiz (improprio)",
    termo_inicial: "Da decisao de deferimento do processamento da recuperacao judicial",
    observacoes: "O edital deve conter: resumo do pedido e da decisao, relacao de credores (se houver), prazo para habilitacoes. A publicacao marca o inicio de diversos prazos para os credores.",
  },
  {
    codigo: "RJ-009",
    nome: "Relatorio previo do administrador judicial (pre-AGC)",
    descricao: "Prazo para o administrador judicial apresentar relatorio previo sobre as condicoes do devedor antes da assembleia geral de credores.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "AUXILIAR",
    subcategoria: "RELATORIO",
    artigo: "Art. 22",
    lei: "Lei 11.101/2005",
    paragrafos: "II, a",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "O juiz pode advertir, destituir ou fixar novo prazo ao AJ",
    termo_inicial: "Fixado pelo juiz, antes da realizacao da AGC",
    observacoes: "O relatorio do AJ deve conter analise da viabilidade do devedor, exame das contas, e parecer sobre as causas e circunstancias da crise. E essencial para subsidiar a votacao dos credores na AGC.",
  },
  {
    codigo: "RJ-010",
    nome: "Prestacao de contas do administrador judicial",
    descricao: "Prazo para o administrador judicial prestar contas ao juiz apos encerramento de suas funcoes.",
    dias: 30,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "AUXILIAR",
    subcategoria: "PRESTACAO_CONTAS",
    artigo: "Art. 22",
    lei: "Lei 11.101/2005",
    paragrafos: "IV",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Responsabilizacao do AJ — possibilidade de nao recebimento da remuneracao ou destituicao",
    termo_inicial: "Do encerramento de suas funcoes como administrador judicial",
    observacoes: "O AJ deve prestar contas detalhadas de sua administracao, incluindo pagamentos efetuados, creditos recebidos e despesas realizadas.",
  },
  {
    codigo: "RJ-011",
    nome: "Pedido de restituicao de bens",
    descricao: "Prazo para o credor titular de bem arrecadado requerer sua restituicao na recuperacao judicial ou falencia.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "RESTITUICAO",
    artigo: "Art. 85",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha prazo peremptorio — pode ser requerido a qualquer tempo ate o encerramento do processo",
    termo_inicial: "A qualquer tempo apos a arrecadacao do bem ate o encerramento da falencia ou da RJ",
    observacoes: "A restituicao depende de comprovacao da propriedade ou posse legitima. O bem deve estar na posse do devedor. Adiantamentos de contrato de cambio e titulos de credito com clausula de reserva de dominio tambem ensejam restituicao.",
  },
  {
    codigo: "RJ-012",
    nome: "Recurso contra decisao que homologa/rejeita o plano",
    descricao: "Prazo para interposicao de agravo de instrumento contra a decisao que concede ou denega a recuperacao judicial.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 59",
    lei: "Lei 11.101/2005 c/c Art. 1.015 CPC",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Transito em julgado da decisao sobre o plano",
    efeito_recursal: "Sem efeito suspensivo automatico",
    termo_inicial: "Da intimacao da decisao que concede ou denega a recuperacao judicial",
    observacoes: "A decisao que concede a recuperacao judicial constitui titulo executivo judicial. O recurso cabivel e o agravo de instrumento (Art. 1.015, paragrafo unico, CPC). Credores e MP tem legitimidade para recorrer.",
  },
  {
    codigo: "RJ-013",
    nome: "Prazo de carencia para novo pedido de recuperacao judicial",
    descricao: "Periodo minimo que deve decorrer entre um pedido de recuperacao judicial e o anterior.",
    dias: 1825,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "CARENCIA",
    artigo: "Art. 48",
    lei: "Lei 11.101/2005",
    paragrafos: "§3o (Lei 14.112/2020)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Inadmissibilidade do novo pedido de recuperacao judicial",
    termo_inicial: "Da concessao da recuperacao judicial anterior (nao do encerramento)",
    observacoes: "O prazo de carencia e de 5 anos da concessao da RJ anterior. Para a RJ do empresario individual, o prazo e de 8 anos. Se o plano anterior foi por cram down (Art. 58 §1), o prazo e de 8 anos.",
  },
  {
    codigo: "RJ-014",
    nome: "Encerramento da recuperacao judicial por cumprimento",
    descricao: "Requerimento de encerramento da recuperacao judicial apos cumprimento das obrigacoes do plano no prazo de 2 anos.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "RJ_ESTATUTARIO",
    subcategoria: "ENCERRAMENTO",
    artigo: "Art. 63",
    lei: "Lei 11.101/2005",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha prazo peremptorio — depende de iniciativa do devedor ou do AJ e decisao judicial",
    termo_inicial: "Apos cumprimento de todas as obrigacoes do plano vencidas no prazo de 2 anos do Art. 61",
    observacoes: "O juiz proferira sentenca de encerramento da recuperacao judicial apos ouvir o AJ e o MP. O devedor continuara obrigado a cumprir o plano quanto as obrigacoes nao vencidas nos 2 anos.",
  },
  {
    codigo: "RJ-015",
    nome: "Convocacao de assembleia geral de credores",
    descricao: "Prazo de antecedencia minima para convocacao da assembleia geral de credores.",
    dias: 15,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "AUXILIAR",
    subcategoria: "ASSEMBLEIA",
    artigo: "Art. 36",
    lei: "Lei 11.101/2005",
    paragrafos: "§1o",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nulidade da assembleia por vicio de convocacao",
    termo_inicial: "O edital deve ser publicado com pelo menos 15 dias de antecedencia da data da AGC",
    observacoes: "A convocacao e feita por edital publicado no orgao oficial e em jornal de grande circulacao. O edital deve conter: local, data e hora da AGC, ordem do dia, local e prazo para consulta de documentos. O quorum de instalacao depende da materia.",
  },

  // =========================================================================
  //  CLT — Prazos trabalhistas
  // =========================================================================
  {
    codigo: "CLT-001",
    nome: "Contestacao trabalhista (defesa em audiencia)",
    descricao: "Prazo para apresentacao da defesa (contestacao) na reclamacao trabalhista — apresentada oralmente ou por escrito na audiencia inaugural.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "RESPOSTA",
    artigo: "Art. 847",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Revelia e confissao ficta (Art. 844 CLT) — presuncao de veracidade dos fatos alegados pelo reclamante",
    termo_inicial: "Na audiencia inaugural (audiencia una ou audiencia inicial em rito ordinario)",
    observacoes: "Na Justica do Trabalho, a contestacao e apresentada em audiencia. Na pratica, muitas varas admitem a juntada de defesa escrita antes da audiencia por meio eletronico. No rito sumarissimo, a audiencia e una. No rito ordinario, pode ser fracionada.",
  },
  {
    codigo: "CLT-002",
    nome: "Recurso ordinario trabalhista",
    descricao: "Prazo para interposicao de recurso ordinario ao TRT contra sentenca de Vara do Trabalho.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 895",
    lei: "CLT",
    admite_dobra: false,
    excecao_dobra: "Na Justica do Trabalho nao se aplica o prazo em dobro do CPC para litisconsortes. Dobra so para Fazenda Publica (Decreto-Lei 779/69)",
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Transito em julgado da sentenca trabalhista",
    efeito_recursal: "Efeito meramente devolutivo (Art. 899 CLT). Efeito suspensivo pode ser requerido excepcionalmente",
    termo_inicial: "Da publicacao/intimacao da sentenca ou da data da audiencia de julgamento",
    observacoes: "O recurso ordinario trabalhista tem prazo de 8 dias CORRIDOS (nao uteis). Exige deposito recursal (Art. 899 §1 CLT) e custas (se vencido). Cuidado: sabado, domingo e feriado nao prorrogam o inicio nem o fim, salvo se o dies a quo cair em dia nao util.",
    jurisprudencia: "Sumula 1 TST — Quando a intimacao tiver lugar na sexta-feira, ou a publicacao com efeito de intimacao for feita nesse dia, o prazo judicial sera contado da segunda-feira imediata.",
    prazo_resposta_dias: 8,
    prazo_resposta_ref: "CLT-007",
  },
  {
    codigo: "CLT-003",
    nome: "Agravo de peticao trabalhista",
    descricao: "Prazo para interposicao de agravo de peticao contra decisao proferida na execucao trabalhista.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 897",
    lei: "CLT",
    paragrafos: "a",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao da decisao proferida na execucao",
    efeito_recursal: "Efeito devolutivo. Sem efeito suspensivo automatico",
    termo_inicial: "Da intimacao da decisao interlocutoria proferida em execucao trabalhista",
    observacoes: "O agravo de peticao e o recurso proprio contra decisoes proferidas na fase de execucao trabalhista. Exige delimitacao justificada das materias e valores impugnados (Art. 897 §1 CLT).",
  },
  {
    codigo: "CLT-004",
    nome: "Agravo de instrumento trabalhista",
    descricao: "Prazo para interposicao de agravo de instrumento contra despacho que denegar seguimento a recurso trabalhista.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 897",
    lei: "CLT",
    paragrafos: "b",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Transito em julgado — denegacao definitiva do recurso",
    efeito_recursal: "Sem efeito suspensivo. Devolutivo restrito ao exame de admissibilidade",
    termo_inicial: "Da intimacao do despacho denegatorio do recurso",
    observacoes: "O agravo de instrumento trabalhista e cabivel contra despacho que denegar seguimento a recurso ordinario, recurso de revista ou recurso extraordinario. Exige deposito recursal quando o recurso trancado tambem o exigia.",
  },
  {
    codigo: "CLT-005",
    nome: "Embargos no TST",
    descricao: "Prazo para interposicao de embargos a decisao de Turma do TST que divergir de outra Turma ou da SDI.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 894",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Transito em julgado do acordao da Turma do TST",
    efeito_recursal: "Efeito devolutivo restrito a divergencia apontada",
    termo_inicial: "Da publicacao do acordao da Turma do TST",
    observacoes: "Embargos de divergencia no TST sao cabíveis quando houver divergência entre Turmas ou entre Turma e SDI, nos termos do Art. 894, II, CLT. Limitados as materias sumuladas ou oriundas de IRDR.",
  },
  {
    codigo: "CLT-006",
    nome: "Recurso de revista",
    descricao: "Prazo para interposicao de recurso de revista ao TST contra acordao de TRT.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "RECURSO",
    artigo: "Art. 896",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Transito em julgado do acordao do TRT",
    efeito_recursal: "Efeito meramente devolutivo. Efeito suspensivo excepcional",
    termo_inicial: "Da publicacao do acordao do TRT",
    observacoes: "O recurso de revista e cabível quando o acordao do TRT: a) der ao texto legal interpretacao diversa da de outro TRT ou do TST; b) contrariar sumula do TST; c) violar literal disposicao de lei federal ou da CF. Exige deposito recursal e custas. Apos a Reforma Trabalhista (Lei 13.467/2017), o cabimento ficou mais restritivo.",
    prazo_resposta_dias: 8,
    prazo_resposta_ref: "CLT-007",
  },
  {
    codigo: "CLT-007",
    nome: "Contrarrazoes trabalhistas",
    descricao: "Prazo para a parte recorrida apresentar contrarrazoes aos recursos trabalhistas.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "CONTRARRAZOES",
    artigo: "Art. 900",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao — perda da oportunidade de contra-arrazoar",
    termo_inicial: "Da intimacao/notificacao da interposicao do recurso",
    observacoes: "O prazo de contrarrazoes e o mesmo do recurso principal: 8 dias corridos. Aplica-se ao RO, RR, agravo de peticao e agravo de instrumento.",
  },
  {
    codigo: "CLT-008",
    nome: "Impugnacao a sentenca de liquidacao trabalhista",
    descricao: "Prazo para impugnacao da sentenca de liquidacao na execucao trabalhista.",
    dias: 8,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 884",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao — homologacao dos calculos de liquidacao",
    termo_inicial: "Da intimacao da sentenca de liquidacao",
    observacoes: "A impugnacao de calculos de liquidacao na Justica do Trabalho segue o rito do Art. 884 CLT. As partes devem apontar especificamente os itens controvertidos.",
  },
  {
    codigo: "CLT-009",
    nome: "Embargos a execucao trabalhista",
    descricao: "Prazo para o executado opor embargos a execucao trabalhista, apos garantia do juizo pela penhora.",
    dias: 5,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "EXECUCAO",
    artigo: "Art. 884",
    lei: "CLT",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Preclusao — prosseguimento da execucao sem possibilidade de defesa por embargos",
    termo_inicial: "Da intimacao da penhora ou da garantia do juizo",
    observacoes: "Os embargos a execucao trabalhista so podem versar sobre: cumprimento da decisao ou acordo; quitacao ou prescricao da divida. Exigem garantia do juizo (penhora). Prazo de 5 dias corridos.",
  },
  {
    codigo: "CLT-010",
    nome: "Mandado de seguranca trabalhista",
    descricao: "Prazo decadencial para impetrar mandado de seguranca na Justica do Trabalho.",
    dias: 120,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 23",
    lei: "Lei 12.016/2009",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Decadencia — perda definitiva do direito de impetrar o mandado de seguranca",
    termo_inicial: "Da data em que o impetrante tiver ciencia oficial do ato coator (intimacao/publicacao)",
    observacoes: "Mandado de seguranca trabalhista e cabível contra ato judicial que nao caiba recurso proprio (Sumula 414 TST). Prazo decadencial de 120 dias corridos. Na Justica do Trabalho, e julgado pelo TRT (se contra juiz de vara) ou TST (se contra desembargador).",
    jurisprudencia: "Sumula 414 TST — E cabível mandado de seguranca contra ato do juiz do trabalho, salvo quando caiba recurso proprio.",
  },

  // =========================================================================
  //  CTN — Prazos tributarios e administrativos
  // =========================================================================
  {
    codigo: "CTN-001",
    nome: "Impugnacao administrativa fiscal (federal)",
    descricao: "Prazo para o contribuinte apresentar impugnacao ao auto de infracao ou notificacao de lancamento no ambito federal.",
    dias: 30,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ADMINISTRATIVO",
    artigo: "Art. 15",
    lei: "Decreto 70.235/1972 (PAF)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "O lancamento torna-se definitivo e o credito tributario sera inscrito em divida ativa",
    termo_inicial: "Da ciencia do auto de infracao ou da notificacao de lancamento",
    observacoes: "A impugnacao instaura a fase litigiosa do processo administrativo fiscal. Tem efeito suspensivo da exigibilidade do credito tributario (Art. 151, III, CTN). Deve ser dirigida a DRJ (Delegacia da Receita Federal de Julgamento).",
  },
  {
    codigo: "CTN-002",
    nome: "Recurso voluntario ao CARF",
    descricao: "Prazo para interposicao de recurso voluntario ao Conselho Administrativo de Recursos Fiscais (CARF).",
    dias: 30,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "RECURSAL",
    subcategoria: "ADMINISTRATIVO",
    artigo: "Art. 33",
    lei: "Decreto 70.235/1972 (PAF)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Transito em julgado administrativo — o credito sera definitivamente constituido e inscrito em divida ativa",
    efeito_recursal: "Efeito suspensivo da exigibilidade do credito tributario (Art. 151, III, CTN)",
    termo_inicial: "Da ciencia da decisao de primeira instancia (DRJ)",
    observacoes: "O recurso voluntario ao CARF mantem a suspensao da exigibilidade do credito. O julgamento e feito por turmas especializadas por materia. Em caso de empate, prevalece a decisao favoravel ao contribuinte (Art. 19-E da Lei 10.522/2002, incluido pela Lei 13.988/2020).",
  },
  {
    codigo: "CTN-003",
    nome: "Mandado de seguranca tributario",
    descricao: "Prazo decadencial para impetrar mandado de seguranca contra ato de autoridade tributaria.",
    dias: 120,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 23",
    lei: "Lei 12.016/2009",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Decadencia — perda definitiva do direito de impetrar o mandado de seguranca (pode ajuizar acao ordinaria)",
    termo_inicial: "Da ciencia do ato coator (notificacao, publicacao do ato, efetiva cobranca)",
    observacoes: "O mandado de seguranca tributario e amplamente utilizado para: questionar exigencias tributarias ilegais, obter CNDs, afastar retencoes indevidas, impedir inscricao em CADIN. Nao comporta dilacao probatoria — a prova deve ser pre-constituida (documental). Exige direito liquido e certo.",
  },
  {
    codigo: "CTN-004",
    nome: "Acao anulatoria de debito fiscal",
    descricao: "Prazo prescricional para ajuizamento de acao anulatoria de debito fiscal.",
    dias: 1825,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "PRESCRICAO",
    artigo: "Art. 169",
    lei: "CTN (Lei 5.172/1966)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Prescricao — impossibilidade de desconstituir o credito tributario por via judicial (se nao ajuizada no prazo)",
    termo_inicial: "Da decisao administrativa que denegar a restituicao (Art. 169 CTN) ou da constituicao definitiva do credito",
    observacoes: "A acao anulatoria de debito fiscal pode ser ajuizada independentemente de deposito do montante integral (Sumula 247 TFR). O deposito integral suspende a exigibilidade (Art. 151, II, CTN), mas nao e requisito para a acao. A prescricao de 5 anos e contada do fato gerador ou da constituicao definitiva.",
  },
  {
    codigo: "CTN-005",
    nome: "Repeticao de indebito tributario",
    descricao: "Prazo prescricional para o contribuinte pleitear a restituicao de tributo pago indevidamente.",
    dias: 1825,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "PRESCRICAO",
    artigo: "Art. 168",
    lei: "CTN (Lei 5.172/1966)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Prescricao — perda definitiva do direito a restituicao do tributo pago indevidamente",
    termo_inicial: "Da data da extincao do credito tributario (data do pagamento indevido — Art. 168, I, CTN) ou da data em que se tornar definitiva a decisao que reformou a decisao condenatoria (Art. 168, II, CTN)",
    observacoes: "A tese dos '5+5' foi superada pelo STJ (LC 118/2005 e RE 566.621 STF). Para pagamentos efetuados apos 09/06/2005, o prazo e de 5 anos contados do pagamento. Aplica-se a repeticao de todos os tributos federais, estaduais e municipais.",
    jurisprudencia: "STJ, Tema 168 (REsp 1.269.570) — Para a repeticao de indebito de tributos sujeitos a lancamento por homologacao pagos apos a LC 118/2005, o prazo prescricional e de 5 anos a contar do pagamento.",
  },
  {
    codigo: "CTN-006",
    nome: "Prescricao para cobranca do credito tributario",
    descricao: "Prazo prescricional para a Fazenda Publica ajuizar execucao fiscal para cobrar credito tributario.",
    dias: 1825,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "PRESCRICAO",
    artigo: "Art. 174",
    lei: "CTN (Lei 5.172/1966)",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Prescricao intercorrente ou originaria — extincao do credito tributario",
    termo_inicial: "Da constituicao definitiva do credito tributario (lancamento definitivo ou decisao administrativa irrecorrivel)",
    observacoes: "A prescricao do credito tributario e materia de ordem publica e pode ser reconhecida de oficio. Interrompe-se por: despacho que ordenar a citacao na execucao fiscal (LC 118/2005), protesto judicial, e demais hipoteses do Art. 174, paragrafo unico, CTN.",
    jurisprudencia: "STJ, Sumula 314 — Em execucao fiscal, nao localizados bens penhoraveis, suspende-se o processo por um ano, findo o qual se inicia o prazo da prescricao quinquenal intercorrente.",
  },

  // =========================================================================
  //  ESPECIAIS — Acoes constitucionais e procedimentos especiais
  // =========================================================================
  {
    codigo: "ESP-001",
    nome: "Mandado de seguranca",
    descricao: "Prazo decadencial para impetrar mandado de seguranca contra ato de autoridade publica ou agente delegado.",
    dias: 120,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 23",
    lei: "Lei 12.016/2009",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Decadencia — perda definitiva do direito ao mandado de seguranca (resta a via ordinaria)",
    termo_inicial: "Da ciencia pelo interessado do ato impugnado (intimacao, publicacao, ou efetivo conhecimento)",
    observacoes: "O prazo de 120 dias e decadencial (nao se suspende nem se interrompe). A impetração e cabivel contra ato de qualquer autoridade publica ou agente de pessoa juridica no exercicio de atribuicoes do poder publico. Exige direito liquido e certo provado por documentos. Nao cabe contra ato judicial recorrivel (Sumula 267 STF).",
    jurisprudencia: "Sumula 632 STF — E constitucional lei que fixa o prazo de decadencia para a impetracao de mandado de seguranca.",
  },
  {
    codigo: "ESP-002",
    nome: "Habeas corpus",
    descricao: "Acao constitucional para protecao da liberdade de locomocao — nao ha prazo para impetrar.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 5, LXVIII",
    lei: "CF/1988 c/c Arts. 647 a 667 CPP",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha prazo — pode ser impetrado a qualquer tempo enquanto houver ameaca ou violacao a liberdade de locomocao",
    termo_inicial: "A qualquer tempo — enquanto subsistir a coacao ou ameaca de coacao a liberdade de locomocao",
    observacoes: "O habeas corpus nao tem prazo de impetração. Pode ser preventivo (ameaca) ou liberatorio (coacao consumada). Nao exige capacidade postulatoria (qualquer pessoa pode impetrar). Tem prioridade de julgamento.",
  },
  {
    codigo: "ESP-003",
    nome: "Acao civil publica",
    descricao: "Acao para tutela de interesses difusos, coletivos e individuais homogeneos — sem prazo prescricional pacifico.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 1",
    lei: "Lei 7.347/1985",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha prazo prescricional pacifico — ha correntes que defendem a imprescritibilidade (ambiental) e outras que aplicam prazo de 5 anos",
    termo_inicial: "Da ciencia da lesao ou ameaca ao interesse difuso, coletivo ou individual homogeneo",
    observacoes: "A prescricao da acao civil publica e tema controvertido. Para danos ambientais, o STJ tem entendido pela imprescritibilidade (REsp 1.120.117). Para outras materias, aplica-se analogicamente o prazo de 5 anos da acao popular. Legitimidade: MP, Defensoria, entes federativos, associacoes.",
    jurisprudencia: "STJ, REsp 1.120.117/AC — E imprescritivel a pretensao de reparacao de dano ambiental, dada a natureza do bem juridico tutelado.",
  },
  {
    codigo: "ESP-004",
    nome: "Acao popular",
    descricao: "Prazo prescricional para ajuizamento de acao popular visando anular ato lesivo ao patrimonio publico.",
    dias: 1825,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Art. 21",
    lei: "Lei 4.717/1965",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Prescricao — impossibilidade de ajuizar a acao popular (o ato permanece valido)",
    termo_inicial: "Da publicacao do ato lesivo ao patrimonio publico",
    observacoes: "A acao popular pode ser ajuizada por qualquer cidadao (eleitor). O prazo de 5 anos e contado da publicacao do ato. O autor popular e isento de custas e onus de sucumbencia, salvo ma-fe.",
  },
  {
    codigo: "ESP-005",
    nome: "Reclamacao constitucional (perante STF ou STJ)",
    descricao: "Medida constitucional para preservar a competencia do STF/STJ e garantir a autoridade de suas decisoes.",
    dias: 0,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "IMPROPRIO",
    categoria: "PARTE",
    subcategoria: "ACAO_CONSTITUCIONAL",
    artigo: "Arts. 102, I, l, e 105, I, f",
    lei: "CF/1988 c/c Art. 988 CPC/2015",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha prazo — cabivel enquanto perdurar a violacao a autoridade do tribunal",
    termo_inicial: "Enquanto perdurar a situacao que a enseja",
    observacoes: "A reclamacao constitucional nao se confunde com a reclamacao do Art. 988 CPC (que e mais ampla). E cabível para: preservar competencia, garantir autoridade de decisao, garantir observancia de sumula vinculante. O STF entende que nao cabe reclamacao como sucedaneo recursal.",
    jurisprudencia: "STF, ADI 2.212 — A reclamacao nao e recurso nem acao, e instrumento de extração constitucional que visa a preservacao da competencia e garantia da autoridade das decisoes do STF.",
  },
  {
    codigo: "ESP-006",
    nome: "Acao rescisoria",
    descricao: "Prazo decadencial para ajuizamento de acao rescisoria visando desconstituir sentenca de merito transitada em julgado.",
    dias: 730,
    contagem_tipo: "DIAS_CORRIDOS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "ACAO_ESPECIAL",
    artigo: "Art. 975",
    lei: "CPC/2015",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Decadencia — a coisa julgada torna-se absolutamente imutavel",
    termo_inicial: "Do transito em julgado da ultima decisao proferida no processo (Art. 975, caput, CPC). Se fundada em prova nova: da data de descoberta da prova nova, observado o prazo maximo de 5 anos do transito em julgado",
    observacoes: "A acao rescisoria e de competencia originaria dos tribunais. Hipoteses taxativas no Art. 966 CPC: violacao manifesta a norma juridica, prevaricacao, prova falsa, prova nova, erro de fato, etc. O deposito de 5% do valor da causa e exigido como condicao de procedibilidade (Art. 968 §1 CPC), exceto para a Fazenda, MP e beneficiarios da justica gratuita.",
    jurisprudencia: "STJ, Sumula 401 — O prazo decadencial da acao rescisoria so se inicia quando nao for cabivel qualquer recurso do ultimo pronunciamento judicial.",
  },
  {
    codigo: "ESP-007",
    nome: "Tutela de urgencia — resposta do reu",
    descricao: "Prazo para o reu se manifestar sobre o pedido de tutela de urgencia antecedente requerida pelo autor.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "TUTELA",
    artigo: "Art. 303",
    lei: "CPC/2015",
    paragrafos: "§1o",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "O juiz decidira sobre a tutela sem a oitiva do reu",
    termo_inicial: "Da citacao do reu no procedimento de tutela antecedente",
    observacoes: "Na tutela de urgencia antecedente (Art. 303 CPC), o autor pode limitar-se a expor o direito ameacado e o perigo de dano, aditando a inicial em 15 dias ou no prazo fixado pelo juiz. O reu sera citado para a audiencia de conciliacao e para contestar.",
  },
  {
    codigo: "ESP-008",
    nome: "Incidente de desconsideracao da personalidade juridica",
    descricao: "Prazo para o socio ou pessoa juridica se manifestar no incidente de desconsideracao da personalidade juridica.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "INCIDENTE",
    artigo: "Art. 135",
    lei: "CPC/2015",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "O juiz decidira o incidente sem a manifestação do socio/pessoa juridica requerida",
    termo_inicial: "Da citacao do socio ou da pessoa juridica no incidente de desconsideracao",
    observacoes: "O IDPJ e cabivel em todas as fases do processo (conhecimento, cumprimento e execucao). Pode ser requerida a desconsideracao direta (para atingir bens do socio) ou inversa (para atingir bens da pessoa juridica). A decisao que resolve o IDPJ e impugnavel por agravo de instrumento (Art. 1.015, IV, CPC).",
  },
  {
    codigo: "ESP-009",
    nome: "Aditamento da inicial na tutela antecedente",
    descricao: "Prazo para o autor aditar a peticao inicial apos deferimento da tutela de urgencia antecedente, complementando a causa de pedir e formulando pedido principal.",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "TUTELA",
    artigo: "Art. 303",
    lei: "CPC/2015",
    paragrafos: "§1, I",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Extincao do processo sem resolucao de merito e cessacao da eficacia da tutela antecedente",
    termo_inicial: "Da efetivacao da tutela de urgencia antecedente deferida",
    observacoes: "O autor deve complementar a argumentacao juridica, confirmar o pedido de tutela e formular o pedido principal. O juiz pode fixar prazo diverso. Se nao aditada, o processo sera extinto.",
  },
  {
    codigo: "ESP-010",
    nome: "Tutela de evidencia — contestacao",
    descricao: "Prazo para contestacao nos casos de tutela da evidencia concedida liminarmente (Art. 311 CPC).",
    dias: 15,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "PEREMPTORIO",
    categoria: "PARTE",
    subcategoria: "TUTELA",
    artigo: "Art. 311",
    lei: "CPC/2015",
    paragrafos: "Paragrafo unico",
    admite_dobra: true,
    admite_litisconsorcio: true,
    efeito_nao_cumprimento: "Revelia — presuncao relativa de veracidade dos fatos e manutencao da tutela",
    termo_inicial: "Da citacao, conforme regras gerais de contestacao (Art. 335 CPC)",
    observacoes: "A tutela da evidencia pode ser concedida liminarmente quando: se tratar de pedido reipersecutorio fundado em prova documental do contrato de deposito; ou quando a peticao estiver instruida com prova documental suficiente e houver tese firmada em julgamento de recursos repetitivos ou sumula vinculante (Art. 311, II e III, CPC).",
  },

  // =========================================================================
  //  PRAZOS ADICIONAIS — Juiz, perito, MP
  // =========================================================================
  {
    codigo: "CPC-JUIZ-001",
    nome: "Prazo para despachos (juiz)",
    descricao: "Prazo para o juiz proferir despachos de mero expediente.",
    dias: 5,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "JUIZ",
    subcategoria: "DESPACHO",
    artigo: "Art. 226",
    lei: "CPC/2015",
    paragrafos: "I",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha preclusao — prazo improprio (sancao administrativa ao juiz, nao processual)",
    termo_inicial: "Da conclusao dos autos",
    observacoes: "Prazo improprio — o descumprimento nao gera nulidade processual, mas pode ensejar correicao parcial e medidas administrativas contra o juiz pelo tribunal.",
  },
  {
    codigo: "CPC-JUIZ-002",
    nome: "Prazo para decisoes interlocutorias (juiz)",
    descricao: "Prazo para o juiz proferir decisoes interlocutorias.",
    dias: 10,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "JUIZ",
    subcategoria: "DECISAO",
    artigo: "Art. 226",
    lei: "CPC/2015",
    paragrafos: "II",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha preclusao — prazo improprio do juiz",
    termo_inicial: "Da conclusao dos autos",
    observacoes: "Inclui decisoes sobre tutelas provisorias, saneamento, etc. Prazo improprio do juiz.",
  },
  {
    codigo: "CPC-JUIZ-003",
    nome: "Prazo para sentenca (juiz)",
    descricao: "Prazo para o juiz proferir sentenca.",
    dias: 30,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "JUIZ",
    subcategoria: "SENTENCA",
    artigo: "Art. 226",
    lei: "CPC/2015",
    paragrafos: "III",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Nao ha preclusao — prazo improprio do juiz. A parte pode peticionar cobrando o cumprimento",
    termo_inicial: "Da conclusao dos autos para sentenca",
    observacoes: "Prazo improprio. Na pratica, juizes frequentemente excedem este prazo. A parte pode requerer providencias ao corregedor. O juiz deve sentenciar preferencialmente na ordem cronologica de conclusao (Art. 12 CPC).",
  },
  {
    codigo: "CPC-PERITO-001",
    nome: "Prazo para entrega do laudo pericial",
    descricao: "Prazo para o perito entregar o laudo pericial, conforme fixado pelo juiz na decisao que deferiu a prova.",
    dias: 20,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "PERITO",
    subcategoria: "LAUDO",
    artigo: "Art. 477",
    lei: "CPC/2015",
    admite_dobra: false,
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Substituicao do perito e possivel responsabilizacao (Art. 468 CPC)",
    termo_inicial: "Fixado pelo juiz na decisao que defere a prova pericial (prazo minimo legal: 20 dias antes da audiencia — Art. 477 CPC)",
    observacoes: "O juiz fixa o prazo para entrega do laudo. O prazo minimo e de 20 dias antes da audiencia de instrucao. O perito pode pedir prorrogação fundamentada. As partes terao 15 dias para se manifestar sobre o laudo (Art. 477 §1 CPC).",
  },
  {
    codigo: "CPC-MP-001",
    nome: "Manifestacao do Ministerio Publico",
    descricao: "Prazo para o Ministerio Publico se manifestar como fiscal da ordem juridica (custos legis).",
    dias: 30,
    contagem_tipo: "DIAS_UTEIS",
    tipo_prazo: "IMPROPRIO",
    categoria: "MP",
    subcategoria: "MANIFESTACAO",
    artigo: "Art. 178",
    lei: "CPC/2015",
    admite_dobra: false,
    excecao_dobra: "O MP ja possui prazo diferenciado — nao se aplica dobra",
    admite_litisconsorcio: false,
    efeito_nao_cumprimento: "Prazo improprio — o juiz pode requisitar manifestacao e comunicar ao PGJ",
    termo_inicial: "Da intimacao pessoal do membro do MP",
    observacoes: "O MP tem prazo em dobro para manifestacao (Art. 180 CPC), ou seja, quando o prazo da parte e 15 dias, o MP tem 30 dias. A intimacao do MP e sempre pessoal (Art. 180 §1 CPC). As hipoteses de intervencao obrigatoria estao no Art. 178 CPC.",
  },
]

async function main() {
  console.log("Seeding deadline catalog...")
  console.log(`Total entries to seed: ${CATALOG_ENTRIES.length}`)

  let created = 0
  let updated = 0

  for (const entry of CATALOG_ENTRIES) {
    const result = await db.deadlineCatalog.upsert({
      where: { codigo: entry.codigo },
      update: {
        ...entry,
        is_system: true,
        ativo: true,
      },
      create: {
        ...entry,
        is_system: true,
        ativo: true,
      },
    })

    // If the record was just created, its created_at and updated_at will be very close
    const timeDiff = result.updated_at.getTime() - result.created_at.getTime()
    if (timeDiff < 1000) {
      created++
    } else {
      updated++
    }
  }

  console.log(`\nSeed complete:`)
  console.log(`  Created: ${created}`)
  console.log(`  Updated: ${updated}`)
  console.log(`  Total:   ${CATALOG_ENTRIES.length}`)
}

main()
  .catch((e) => {
    console.error("Error seeding deadline catalog:", e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
